/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'audit-events': AuditEvent;
    media: Media;
    works: Work;
    'radar-public-conclusions': RadarPublicConclusion;
    'radar-public-records': RadarPublicRecord;
    'radar-public-ratings': RadarPublicRating;
    creators: Creator;
    organizations: Organization;
    evidence: Evidence;
    'stewardship-notices': StewardshipNotice;
    'radar-research-records': RadarResearchRecord;
    comments: Comment;
    'user-lists': UserList;
    'feedback-submissions': FeedbackSubmission;
    terms: Term;
    warnings: Warning;
    tags: Tag;
    rules: Rule;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'radar-public-conclusions': RadarPublicConclusionsSelect<false> | RadarPublicConclusionsSelect<true>;
    'radar-public-records': RadarPublicRecordsSelect<false> | RadarPublicRecordsSelect<true>;
    'radar-public-ratings': RadarPublicRatingsSelect<false> | RadarPublicRatingsSelect<true>;
    creators: CreatorsSelect<false> | CreatorsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    evidence: EvidenceSelect<false> | EvidenceSelect<true>;
    'stewardship-notices': StewardshipNoticesSelect<false> | StewardshipNoticesSelect<true>;
    'radar-research-records': RadarResearchRecordsSelect<false> | RadarResearchRecordsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'user-lists': UserListsSelect<false> | UserListsSelect<true>;
    'feedback-submissions': FeedbackSubmissionsSelect<false> | FeedbackSubmissionsSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    warnings: WarningsSelect<false> | WarningsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    rules: RulesSelect<false> | RulesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'owner' | 'admin' | 'editor' | 'member';
  accountStatus: 'active' | 'suspended';
  suspensionReason?: string | null;
  suspendedAt?: string | null;
  suspendedBy?: (number | null) | User;
  displayName?: string | null;
  termsAcceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 记录内容、账户和互动写入的操作者、对象与变更摘要。仅管理人员可见，不能从后台手工伪造。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor: number | User;
  action: string;
  targetCollection: string;
  targetID: string;
  targetTitle?: string | null;
  summary?: string | null;
  /**
   * 只保存必要的字段差异；不要写入密码、token 或完整证据图片。
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  /**
   * 低流量正式版不渲染封面和证据图片；增强媒体版可按用途展示。
   */
  mediaScope: 'site-ui' | 'cover' | 'evidence' | 'legacy' | 'full-only';
  /**
   * 外部来源中的原始文件名。
   */
  originalFilename?: string | null;
  /**
   * 记录图片来源、证据说明和整理备注等。
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  /**
   * 仅用于旧链接兼容和导入匹配。公开规范网址使用本站 Works 数据库 ID。
   */
  slug: string;
  /**
   * 历史导入与跨来源合并用的追踪值；不作为公开网址，也不等于 Works 数据库主键。
   */
  siteId?: string | null;
  rank: 'S' | 'AA' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'trash' | 'unknown';
  /**
   * 与 AI Radar 独立保存。人工审核是可追溯的参考意见，不会覆盖 AI 轨道；目录展示优先采用人工等级，但两条证据始终分别呈现。
   */
  humanAssessment?: {
    grade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'unknown') | null;
    status?: ('pending' | 'reviewed' | 'disputed') | null;
    note?: string | null;
    sourceSummary?: string | null;
    evidenceStatus?: ('unassessed' | 'source_checked' | 'primary_checked' | 'insufficient') | null;
    sourceLinks?:
      | {
          label?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    assessedAt?: string | null;
    assessedBy?: (number | null) | User;
  };
  /**
   * 旧字段兼容状态；新的人工意见请填写 humanAssessment，AI Radar 保留在 radarAssessment。
   */
  reviewStatus: 'pending' | 'reviewed' | 'disputed' | 'deprecated';
  /**
   * 记录本次人工复核的结论、仍待确认的问题或退回原因。
   */
  humanReviewNote?: string | null;
  humanReviewedAt?: string | null;
  humanReviewedBy?: (number | null) | User;
  /**
   * 记录批量导入、预览或迁移批次，例如 public-catalog-import-v02。用于内部复核筛选。
   */
  importBatch?: string | null;
  /**
   * 记录导入阶段给出的分级提示，例如 AI 综合待复核或信息不足。
   */
  ratingNotice?:
    ('ai_synthesized_pending_review' | 'insufficient_information' | 'manual_reviewed' | 'none' | 'other') | null;
  /**
   * 记录本条导入记录采用的基准来源。候选来源详情仍保存在 candidateSources。
   */
  chosenBaseSource?:
    | (
        | 'yurizukan'
        | 'bangumi'
        | 'mangadex'
        | 'ndl'
        | 'steam'
        | 'wikidata'
        | 'anilist'
        | 'vndb'
        | 'wikipedia'
        | 'manual'
        | 'other'
      )
    | null;
  /**
   * 结构化记录进入复核队列的原因；用于内部 review dashboard 精确筛选。
   */
  reviewReasons?:
    | (
        | 'radar_seed_attached'
        | 'radar_v06_package_import'
        | 'radar_publication_guard'
        | 'radar_guard_low_evidence_coverage'
        | 'radar_guard_weak_or_conflicting_source'
        | 'radar_guard_unclear_provisional_grade'
        | 'source_conflict'
        | 'multi_source_or_variant'
        | 'wikidata_candidate_review'
        | 'wikidata_quarantine'
        | 'manual_review'
        | 'other'
      )[]
    | null;
  /**
   * 记录多来源、变体、冲突来源等简要说明。
   */
  sourceConflictNotes?: string | null;
  /**
   * 按本站当前证据材料评估强弱；未评估不等于没有证据。
   */
  evidenceStrength: 'unassessed' | 'weak' | 'medium' | 'strong';
  /**
   * 作品原始标题，例如日文、英文、韩文原名。
   */
  originalTitle?: string | null;
  aliases?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于记录原名、官方译名、地区译名、罗马字、民间译名和仅搜索名称；不是完整多语言站点内容。
   */
  localizedTitles?:
    | {
        title: string;
        language?:
          ('ja' | 'zh-Hans' | 'zh-Hant' | 'en' | 'ko' | 'fr' | 'de' | 'es' | 'und' | 'other' | 'unknown') | null;
        /**
         * 可填 JP、CN、TW、HK、US 等，也可留空。
         */
        region?: string | null;
        kind?:
          | (
              | 'original'
              | 'official'
              | 'localized'
              | 'romanized'
              | 'alias'
              | 'fan'
              | 'literal'
              | 'search_only'
              | 'other'
            )
          | null;
        isPrimary?: boolean | null;
        /**
         * 例如 Bangumi、AniList、VNDB、Wikidata、manual。
         */
        source?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 前台筛选用的大类：动画、漫画、小说、游戏等。后续导入可由作品类型自动推导。
   */
  mediaGroup?: ('anime' | 'manga' | 'novel' | 'game' | 'other' | 'unknown') | null;
  /**
   * 用于区分动画、漫画、小说、游戏、视觉小说等候选作品底板类型。
   */
  mediaType:
    | 'anime'
    | 'manga'
    | 'novel'
    | 'light_novel'
    | 'visual_novel'
    | 'game'
    | 'audio_drama'
    | 'live_action'
    | 'webtoon'
    | 'doujin'
    | 'anthology'
    | 'other'
    | 'unknown';
  /**
   * 比作品类型更细的形态，例如 TV 动画、漫画连载、视觉小说、手机游戏等。
   */
  format?:
    | (
        | 'tv_anime'
        | 'anime_movie'
        | 'ova'
        | 'ona'
        | 'manga_series'
        | 'manga_oneshot'
        | 'novel_series'
        | 'light_novel_series'
        | 'web_serial'
        | 'visual_novel'
        | 'pc_game'
        | 'console_game'
        | 'mobile_game'
        | 'audio_drama'
        | 'live_action'
        | 'webtoon_series'
        | 'doujin'
        | 'anthology'
        | 'other'
        | 'unknown'
      )
    | null;
  /**
   * 用于排序的机器日期。若只知道年份，可先填当年 1 月 1 日，并用日期精度和显示文本说明。
   */
  firstPublishedAt?: string | null;
  /**
   * 避免把只知道年份或月份的外部数据误显示成精确日期。
   */
  firstPublishedPrecision?: ('day' | 'month' | 'year' | 'unknown') | null;
  /**
   * 前台可优先显示这个文本，例如 2015、2015-04、2018-10-05、待定。
   */
  firstPublishedLabel?: string | null;
  /**
   * 用于候选导入、去重和跨来源对齐，不直接代表本站复核结论。
   */
  externalIds?: {
    bangumiSubjectId?: string | null;
    anilistMediaId?: string | null;
    vndbId?: string | null;
    wikidataQid?: string | null;
    malId?: string | null;
    officialUrl?: string | null;
  };
  /**
   * 记录候选作品来自哪些外部来源。这里只保存来源链接和派生说明，不保存用户评论原文。
   */
  candidateSources?:
    | {
        source?:
          | (
              | 'yurizukan'
              | 'bangumi'
              | 'mangadex'
              | 'ndl'
              | 'steam'
              | 'wikidata'
              | 'anilist'
              | 'vndb'
              | 'wikipedia'
              | 'manual'
              | 'other'
            )
          | null;
        label?: string | null;
        externalId?: string | null;
        url?: string | null;
        fetchedAt?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 候选导入阶段生成的系列/条目归组提示，仅供后台复核；不代表已经确认公开系列导航。
   */
  workGroup?: {
    key?: string | null;
    title?: string | null;
    relation?: string | null;
    orderLabel?: string | null;
    source?: string | null;
    confidence?: string | null;
    note?: string | null;
  };
  /**
   * 0 到 1 的候选强度分，只用于底板导入和复核排序，不代表本站评级。
   */
  yuriCandidateScore?: number | null;
  /**
   * 关闭后不进入低成本文字主站。
   */
  isLiteVisible?: boolean | null;
  /**
   * 完整版现在默认收录全部记录；此字段仅为旧导出器与历史数据兼容保留。
   */
  isFullVisible?: boolean | null;
  /**
   * 用于提示 Full 版是否存在截图、附件或来源材料。
   */
  hasEvidence?: boolean | null;
  /**
   * 用于作品页快速展示核心排雷维度；没有把握时保持未评估即可。
   */
  riskMatrix?: {
    maleImpact?: ('unassessed' | 'none' | 'minor' | 'noticeable' | 'severe') | null;
    relationshipClarity?: ('unassessed' | 'confirmed' | 'developing' | 'subtext' | 'friendship' | 'unclear') | null;
    endingSafety?: ('unassessed' | 'safe' | 'open' | 'unfinished' | 'risky' | 'bad') | null;
    creatorSpeechRisk?: ('unassessed' | 'none' | 'minor' | 'disputed' | 'severe') | null;
    /**
     * 简短说明矩阵判断依据；详细材料仍放到证据材料和材料留存。
     */
    note?: string | null;
  };
  creators?: (number | Creator)[] | null;
  /**
   * 记录会影响剧情、设定或表达方向的关键动画职位，例如监督、总监督、系列构成、脚本、原作等。
   */
  creatorCredits?:
    | {
        creator: number | Creator;
        role:
          | 'original_creator'
          | 'original_concept'
          | 'director'
          | 'chief_director'
          | 'series_director'
          | 'series_composition'
          | 'script'
          | 'character_original_design'
          | 'character_design'
          | 'producer'
          | 'other';
        /**
         * 保留来源里的原文职位，例如 監督、総監督、シリーズ構成、脚本。
         */
        originalRole?: string | null;
        source?:
          | (
              | 'yurizukan'
              | 'bangumi'
              | 'mangadex'
              | 'ndl'
              | 'steam'
              | 'wikidata'
              | 'anilist'
              | 'vndb'
              | 'wikipedia'
              | 'manual'
              | 'other'
            )
          | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 出版社、制作公司、发行商、平台、制作委员会、委员会成员、电视台、音乐厂牌等机构关系。
   */
  organizations?:
    | {
        organization: number | Organization;
        role:
          | 'publisher'
          | 'production_company'
          | 'animation_studio'
          | 'game_developer'
          | 'distributor'
          | 'circle'
          | 'brand'
          | 'platform'
          | 'streaming_platform'
          | 'broadcaster'
          | 'committee'
          | 'committee_member'
          | 'music_label'
          | 'investor'
          | 'rights_holder'
          | 'other';
        /**
         * 保留来源里的原文角色，例如 製作、制作、放送、音楽制作、制作委员会成员等。
         */
        originalRole?: string | null;
        source?:
          | (
              | 'yurizukan'
              | 'bangumi'
              | 'mangadex'
              | 'ndl'
              | 'steam'
              | 'wikidata'
              | 'anilist'
              | 'vndb'
              | 'wikipedia'
              | 'manual'
              | 'other'
            )
          | null;
        /**
         * 可记录具体名义、系列品牌、委员会成员说明或迁移备注。
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?: (number | Tag)[] | null;
  warnings?: (number | Warning)[] | null;
  cover?: (number | null) | Media;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  analysis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sourceLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于导出前台搜索索引的补充文本，不在数据库中建立 btree 索引。可放日文名、英文名、别名、作者名、关键词等。
   */
  searchText?: string | null;
  /**
   * 先记录证据材料说明；后续可迁移到独立 evidence collection。
   */
  evidenceNote?: string | null;
  /**
   * 正式与临时作品都保持发布并进入前台；临时表示事实资料已入库、仍待补齐或复核。归档才会从前台隐藏。
   */
  catalogStatus: 'active' | 'temporary' | 'archived';
  /**
   * 可选。用于身份争议、版本差异、站务裁量、用语说明或其他特殊提醒；可以关联多条。
   */
  stewardshipNotices?: (number | StewardshipNotice)[] | null;
  /**
   * 保存当前排雷判断、命中规则、置信度、资料覆盖度和证据状态。这里的百分比不表示作品安全概率。
   */
  radarAssessment?: {
    /**
     * 表示当前建议与现有证据的一致程度，不等同于作品安全概率。
     */
    confidencePercent?: number | null;
    /**
     * 表示角色关系、剧情发展、结局、官方说明和来源材料等关键证据的完整度。
     */
    evidenceCoveragePercent?: number | null;
    evidenceStatus?:
      | (
          | 'official_confirmed'
          | 'primary_material_confirmed'
          | 'multiple_secondary_supported'
          | 'single_secondary_supported'
          | 'community_consensus'
          | 'inferred_from_metadata'
          | 'conflicting_evidence'
          | 'insufficient_evidence'
          | 'unknown'
        )
      | null;
    /**
     * 面向读者的简短来源说明；具体链接仍放在来源链接或候选来源中。
     */
    sourceSummary?: string | null;
    sourceCount?: number | null;
    /**
     * 例如 radar-rating-policy-v0.4-draft。
     */
    policyVersion?: string | null;
    /**
     * 用于回溯产生本次建议的暂存批次。
     */
    assessmentBatch?: string | null;
    /**
     * 保存本次规则解析建议；人工确认前仍受分级提示和复核状态约束。
     */
    suggestedGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X') | null;
    decisiveRuleCode?: string | null;
    decisiveRuleReason?: string | null;
    /**
     * 保留全部命中的子规则；最低安全等级只决定建议等级，不会丢弃其他命中项。
     */
    matchedRules?:
      | {
          code: string;
          grade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X';
          confidencePercent?: number | null;
          reason?: string | null;
          id?: string | null;
        }[]
      | null;
    contradictions?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    requiresHumanReview?: boolean | null;
    assessedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators".
 */
export interface Creator {
  id: number;
  name: string;
  /**
   * 仅用于旧链接兼容和导入匹配。公开规范网址使用本站 Creators 数据库 ID。
   */
  slug: string;
  /**
   * 历史导入与跨来源合并用的追踪值；不作为公开网址，也不等于 Creators 数据库主键。
   */
  siteId?: string | null;
  rank?: ('S' | 'AA' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'unknown') | null;
  /**
   * 只有完成逐条人工核验后才能改为“已复核”。
   */
  reviewStatus: 'pending' | 'reviewed' | 'disputed' | 'deprecated';
  /**
   * 标记资料由谁整理；AI 已评估不等于人工通过。
   */
  reviewOrigin: 'unassessed' | 'ai_assessed' | 'human_reviewed' | 'imported_unverified';
  humanReviewNote?: string | null;
  humanReviewedAt?: string | null;
  humanReviewedBy?: (number | null) | User;
  aliases?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于记录原名、官方名、地区名、罗马字、旧名和仅搜索名称；不要求每种语言都填写。
   */
  localizedNames?:
    | {
        name: string;
        language?:
          ('ja' | 'zh-Hans' | 'zh-Hant' | 'en' | 'ko' | 'fr' | 'de' | 'es' | 'und' | 'other' | 'unknown') | null;
        /**
         * 可填 JP、CN、TW、HK、US 等，也可留空。
         */
        region?: string | null;
        kind?:
          | (
              | 'original'
              | 'official'
              | 'localized'
              | 'romanized'
              | 'alias'
              | 'legal'
              | 'former'
              | 'search_only'
              | 'other'
            )
          | null;
        isPrimary?: boolean | null;
        /**
         * 例如 Bangumi、AniList、VNDB、Wikidata、manual。
         */
        source?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  profileImage?: (number | null) | Media;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 用于导出前台搜索索引的补充文本，可放别名、社团名、历史名称、作品关键词等。
   */
  searchText?: string | null;
  isLiteVisible?: boolean | null;
  /**
   * 完整版现默认收录全部记录；仅为旧导出器兼容保留。
   */
  isFullVisible?: boolean | null;
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * 可选。用于身份争议、版本差异、站务裁量、用语说明或其他特殊提醒；可以关联多条。
   */
  stewardshipNotices?: (number | StewardshipNotice)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stewardship-notices".
 */
export interface StewardshipNotice {
  id: number;
  title: string;
  /**
   * 用于导入、样式和长期追踪。创建后尽量不要修改，例如 identity-conflict。
   */
  slug: string;
  category: 'operation' | 'terminology' | 'identity' | 'editorial' | 'content' | 'transparency' | 'other';
  tone: 'note' | 'warning' | 'danger' | 'black-banner';
  severity: 'low' | 'medium' | 'high' | 'critical';
  /**
   * 直接显示在条目标题与基础资料之间，应当简洁、可独立理解。
   */
  summary: string;
  /**
   * 可选。用于解释适用范围、站务依据和后续处理方式。
   */
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 可选。可以指向站点说明、透明度报告、规则页或其他公开页面。
   */
  helpUrl?: string | null;
  /**
   * 用于编辑提示，不作为强制限制；同一提示可适用于多个页面类型。
   */
  applicableCollections?: ('works' | 'creators' | 'organizations')[] | null;
  /**
   * 数字越小越靠前。关键提示建议使用 0–20。
   */
  sortOrder?: number | null;
  /**
   * 关闭时保留历史记录，但普通用户不可见，也不会出现在日常编辑选择器中。
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * 仅用于旧链接兼容和导入匹配。公开规范网址使用本站 Organizations 数据库 ID。
   */
  slug: string;
  /**
   * 历史导入与跨来源合并用的追踪值；不作为公开网址，也不等于 Organizations 数据库主键。
   */
  siteId?: string | null;
  type:
    | 'publisher'
    | 'production_company'
    | 'animation_studio'
    | 'game_company'
    | 'distributor'
    | 'circle'
    | 'brand'
    | 'platform'
    | 'committee'
    | 'other';
  /**
   * 只有完成逐条人工核验后才能改为“已复核”。
   */
  reviewStatus: 'pending' | 'reviewed' | 'disputed' | 'deprecated';
  /**
   * 标记资料由谁整理；AI 已评估不等于人工通过。
   */
  reviewOrigin: 'unassessed' | 'ai_assessed' | 'human_reviewed' | 'imported_unverified';
  humanReviewNote?: string | null;
  humanReviewedAt?: string | null;
  humanReviewedBy?: (number | null) | User;
  aliases?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于记录原名、官方名、地区名、罗马字、旧名和仅搜索名称；不要求每种语言都填写。
   */
  localizedNames?:
    | {
        name: string;
        language?:
          ('ja' | 'zh-Hans' | 'zh-Hant' | 'en' | 'ko' | 'fr' | 'de' | 'es' | 'und' | 'other' | 'unknown') | null;
        /**
         * 可填 JP、CN、TW、HK、US 等，也可留空。
         */
        region?: string | null;
        kind?:
          | (
              | 'original'
              | 'official'
              | 'localized'
              | 'romanized'
              | 'alias'
              | 'legal'
              | 'former'
              | 'search_only'
              | 'other'
            )
          | null;
        isPrimary?: boolean | null;
        /**
         * 例如 Bangumi、AniList、VNDB、Wikidata、manual。
         */
        source?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sourceLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于导出前台搜索索引的补充文本，可放别名、历史名称、官网名、品牌名和作品关键词等。
   */
  searchText?: string | null;
  isLiteVisible?: boolean | null;
  /**
   * 完整版现默认收录全部记录；仅为旧导出器兼容保留。
   */
  isFullVisible?: boolean | null;
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * 可选。用于身份争议、版本差异、站务裁量、用语说明或其他特殊提醒；可以关联多条。
   */
  stewardshipNotices?: (number | StewardshipNotice)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * 用于 URL 和导入匹配，例如 magical-girl。
   */
  slug: string;
  /**
   * 本站内部稳定唯一标识，用于迁移、导入、跨来源合并和人工追踪。
   */
  siteId?: string | null;
  category: 'general' | 'genre' | 'medium' | 'relationship' | 'style' | 'status';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warnings".
 */
export interface Warning {
  id: number;
  name: string;
  slug: string;
  /**
   * 本站内部稳定唯一标识，用于迁移、导入、跨来源合并和人工追踪。
   */
  siteId?: string | null;
  severity: 'low' | 'medium' | 'high' | 'critical';
  category: 'content' | 'relationship' | 'creator' | 'operation' | 'other';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedTerms?: (number | Term)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  name: string;
  slug: string;
  /**
   * 本站内部稳定唯一标识，用于导入、跨来源合并和人工追踪。
   */
  siteId?: string | null;
  isLiteVisible?: boolean | null;
  /**
   * 完整版现默认收录全部记录；仅为旧导出器兼容保留。
   */
  isFullVisible?: boolean | null;
  definition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  examples?: (number | Work)[] | null;
  relatedWarnings?: (number | Warning)[] | null;
  relatedTerms?: (number | Term)[] | null;
  /**
   * 用于导出前台搜索索引的补充文本。
   */
  searchText?: string | null;
  legacyXWikiPage?: string | null;
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 面向前台的当前 AI Radar 结论投影。每个作品只保留一条当前记录；更新此集合不会写入 Works 或提升 Works 草稿。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-public-conclusions".
 */
export interface RadarPublicConclusion {
  id: number;
  /**
   * 稳定幂等键，固定使用 work:<Works 数据库 ID>。新 AI 结论更新同一条记录。
   */
  publicationKey: string;
  work: number | Work;
  workIdSnapshot: string;
  workSiteId?: string | null;
  title: string;
  recordStatus: 'current' | 'withdrawn';
  conclusionMode: 'fixed_grade' | 'bounded_range';
  /**
   * 固定等级直接使用该等级；有界范围使用最可能等级。人工轨道仍在前台优先。
   */
  compatibilityGrade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'unknown';
  bestGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'unknown') | null;
  likelyGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'unknown') | null;
  worstGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'unknown') | null;
  ratingNotice: 'ai_synthesized_pending_review' | 'insufficient_information' | 'none';
  reviewReasons?:
    | (
        | 'radar_v06_package_import'
        | 'radar_publication_guard'
        | 'radar_guard_low_evidence_coverage'
        | 'radar_guard_weak_or_conflicting_source'
        | 'radar_guard_unclear_provisional_grade'
      )[]
    | null;
  evidenceStrength: 'unassessed' | 'weak' | 'medium' | 'strong';
  /**
   * 保存当前排雷判断、命中规则、置信度、资料覆盖度和证据状态。这里的百分比不表示作品安全概率。
   */
  radarAssessment?: {
    /**
     * 表示当前建议与现有证据的一致程度，不等同于作品安全概率。
     */
    confidencePercent?: number | null;
    /**
     * 表示角色关系、剧情发展、结局、官方说明和来源材料等关键证据的完整度。
     */
    evidenceCoveragePercent?: number | null;
    evidenceStatus?:
      | (
          | 'official_confirmed'
          | 'primary_material_confirmed'
          | 'multiple_secondary_supported'
          | 'single_secondary_supported'
          | 'community_consensus'
          | 'inferred_from_metadata'
          | 'conflicting_evidence'
          | 'insufficient_evidence'
          | 'unknown'
        )
      | null;
    /**
     * 面向读者的简短来源说明；具体链接仍放在来源链接或候选来源中。
     */
    sourceSummary?: string | null;
    sourceCount?: number | null;
    /**
     * 例如 radar-rating-policy-v0.4-draft。
     */
    policyVersion?: string | null;
    /**
     * 用于回溯产生本次建议的暂存批次。
     */
    assessmentBatch?: string | null;
    /**
     * 保存本次规则解析建议；人工确认前仍受分级提示和复核状态约束。
     */
    suggestedGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X') | null;
    decisiveRuleCode?: string | null;
    decisiveRuleReason?: string | null;
    /**
     * 保留全部命中的子规则；最低安全等级只决定建议等级，不会丢弃其他命中项。
     */
    matchedRules?:
      | {
          code: string;
          grade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X';
          confidencePercent?: number | null;
          reason?: string | null;
          id?: string | null;
        }[]
      | null;
    contradictions?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    requiresHumanReview?: boolean | null;
    assessedAt?: string | null;
  };
  sourceKind: 'package' | 'latest_ai_draft' | 'manual_ai_update';
  sourcePackageId?: string | null;
  sourcePackageSha256?: string | null;
  conclusionSha256: string;
  publicationVersion: string;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 注册用户可只读当前研究投影；编辑以上可检查撤回记录。保存已核实事实、来源与资料不足状态；不会覆盖 Works、人工评级或旧 Radar 评级。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-public-records".
 */
export interface RadarPublicRecord {
  id: number;
  /**
   * 固定使用 work:<Works 数据库 ID>；后续发布包幂等更新同一条记录。
   */
  publicationKey: string;
  work: number | Work;
  /**
   * 精确 workId|siteId 身份；禁止标题近似匹配与版本替换。
   */
  identityKey: string;
  workIdSnapshot: string;
  workSiteId: string;
  title: string;
  publicState: 'verified' | 'partial' | 'needs_more_research';
  researchStatus: 'ready_for_publication' | 'partially_verified' | 'needs_more_research';
  pageNotice: string;
  facts?:
    | {
        factId: string;
        factType: string;
        /**
         * 统一 Release 的公开事实值是原样文本；不得在导入时包装成 JSON 对象或改变内容。
         */
        value: string;
        sourceRefs: {
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  evidence?:
    | {
        sourceRef: string;
        tier: 'A' | 'B' | 'C' | 'D' | 'E';
        role: 'primary' | 'licensed_or_authorized' | 'supplemental' | 'lead_only';
        url: string;
        title: string;
        exactIdentityBound: boolean;
        id?: string | null;
      }[]
    | null;
  sourceReleaseId: string;
  sourceCommitSha: string;
  sourcePolicyVersion: string;
  researchSnapshotId: string;
  recordSha256: string;
  releaseRecordsSha256: string;
  sourceReviewedAt: string;
  importedAt: string;
  recordStatus: 'current' | 'withdrawn';
  updatedAt: string;
  createdAt: string;
}
/**
 * 独立保存公开机器评级、规则类别、标签提示与来源哈希；不覆盖 Works 的 AI 或人工评级字段。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-public-ratings".
 */
export interface RadarPublicRating {
  id: number;
  /**
   * 固定使用 work:<Works 数据库 ID>；后续发布包幂等更新同一条评级记录。
   */
  publicationKey: string;
  work: number | Work;
  /**
   * 精确 workId|siteId 身份；禁止标题近似匹配与版本替换。
   */
  identityKey: string;
  workIdSnapshot: string;
  workSiteId: string;
  title: string;
  coreGrade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X';
  bestGrade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X';
  likelyGrade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X';
  worstGrade: 'S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X';
  confidence: 'high' | 'medium' | 'low';
  matchedClasses?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  factRefs?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  evidenceRefs?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  reasoningSummary: string;
  unresolvedDimensions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  classificationRule: string;
  confirmationBasis?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  benefitOfDoubtBaselineApplied: boolean;
  publicTagHints?:
    | {
        key: string;
        group: string;
        value: string;
        warningTemplateId?: string | null;
        id?: string | null;
      }[]
    | null;
  publicWarningTemplateIds?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  humanReview: {
    status: 'unreviewed' | 'reviewed' | 'disputed';
    reviewerIdentity?: string | null;
    reviewedAt?: string | null;
    decision?: string | null;
    proposedCoreGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X') | null;
    proposedProfileChanges?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    reasoning?: string | null;
    additionalEvidenceRefs?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    moderationState?: string | null;
    blocksAnalysis: boolean;
    blocksPublication: boolean;
  };
  sourceReleaseId: string;
  sourceCommitSha: string;
  sourcePolicyVersion: string;
  researchSnapshotId: string;
  sourceRatingCampaignId: string;
  sourceRatingDecisionHash: string;
  releaseRatingHash: string;
  releaseRatingsSha256: string;
  importedAt: string;
  recordStatus: 'current' | 'withdrawn';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence".
 */
export interface Evidence {
  id: number;
  title: string;
  /**
   * 用于导入匹配和详情页 URL。
   */
  slug: string;
  /**
   * 本站内部稳定唯一标识，用于导入、跨来源合并和人工追踪。
   */
  siteId?: string | null;
  evidenceType:
    'work_screenshot' | 'official_page' | 'interview' | 'social_media' | 'legacy_wiki' | 'platform_page' | 'other';
  /**
   * 本站的人工复核状态。
   */
  reviewStatus: 'pending' | 'reviewed' | 'disputed' | 'deprecated';
  /**
   * 按本站当前证据材料评估强弱；未评估不等于没有证据。
   */
  evidenceStrength: 'unassessed' | 'weak' | 'medium' | 'strong';
  relatedWorks?: (number | Work)[] | null;
  relatedCreators?: (number | Creator)[] | null;
  relatedOrganizations?: (number | Organization)[] | null;
  /**
   * 用于内部材料留存和增强媒体版；低流量正式版不会公开渲染。
   */
  image?: (number | null) | Media;
  description?: string | null;
  sourceLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 记录截图或取证的大致时间。
   */
  capturedAt?: string | null;
  /**
   * 关闭时只作为后台整理材料。低流量正式版无论此项如何都不渲染图片。
   */
  isPublic?: boolean | null;
  /**
   * 用于导出搜索索引的补充文本。
   */
  searchText?: string | null;
  status: 'draft' | 'review' | 'confirmed' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 保存 AI Radar 的内部研究分诊结果。默认不公开，也不等同于正式评级。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-research-records".
 */
export interface RadarResearchRecord {
  id: number;
  /**
   * programId|workId|siteId。用于幂等导入和后续研究版本并存。
   */
  researchKey: string;
  title: string;
  programId: string;
  importBatch: string;
  batchId: string;
  wave?: string | null;
  lane?: string | null;
  milestone?: number | null;
  work: number | Work;
  workIdSnapshot: string;
  workSiteId: string;
  recordShape: 'blocked' | 'catalog';
  researchStatus: 'resolved' | 'partial' | 'insufficient' | 'identity_problem';
  yuriRelevance?: ('high' | 'possible' | 'unknown') | null;
  riskSignals?:
    ('male_involvement' | 'ntr' | 'futa' | 'otokonoko' | 'ts' | 'prior_male_relationship' | 'abo' | 'other')[] | null;
  proposedLikelyGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'unknown') | null;
  proposedBestGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'unknown') | null;
  proposedWorstGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'unknown') | null;
  sourceSummary?: string | null;
  sources?:
    | {
        title?: string | null;
        url: string;
        sourceType?: ('official' | 'primary' | 'secondary' | 'community' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  unresolvedQuestions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  confidencePercent?: number | null;
  recommendedNextAction?: ('promote_for_reassessment' | 'retain_block' | 'human_review' | 'identity_review') | null;
  recommendedNextQueue?: ('full_assessment' | 'more_research' | 'low_priority') | null;
  researchNote?: string | null;
  sourceResponseSha256: string;
  importedAt: string;
  recordStatus: 'current' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  targetCollection: 'works' | 'creators' | 'organizations' | 'evidence' | 'terms' | 'rules';
  targetSlug: string;
  targetTitle: string;
  /**
   * 回复统一归到一层主评论下，避免手机端无限嵌套。
   */
  parentComment?: (number | null) | Comment;
  replyToName?: string | null;
  /**
   * 仅用于账户消息提醒；由服务器根据被回复评论的作者写入，不对公共评论 API 暴露。
   */
  replyToUser?: (number | null) | User;
  author?: (number | null) | User;
  authorName?: string | null;
  /**
   * 短评、阅读感想，或提醒条目需要复核。纯文本，提交后立即公开。
   */
  body: string;
  moderationStatus: 'pending' | 'approved' | 'rejected' | 'hidden';
  /**
   * 达到自动保护阈值后评论会暂时隐藏，工作人员可恢复或删除。
   */
  reportCount?: number | null;
  reportedBy?: (number | User)[] | null;
  hiddenReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-lists".
 */
export interface UserList {
  id: number;
  user: number | User;
  workSlug: string;
  workTitle: string;
  listStatus: 'want' | 'watching' | 'seen' | 'favorite' | 'avoid' | 'needs_review';
  /**
   * 仅用于自己的列表记录。
   */
  note?: string | null;
  /**
   * 用户和作品 slug 组成的唯一键，用于避免重复加入同一作品。
   */
  uniqueKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-submissions".
 */
export interface FeedbackSubmission {
  id: number;
  feedbackType:
    | 'radar_evidence'
    | 'rating_correction'
    | 'new_work'
    | 'content_correction'
    | 'broken_link'
    | 'display_problem'
    | 'other';
  targetCollection?: string | null;
  targetSlug?: string | null;
  targetTitle: string;
  /**
   * 仅用于新增作品建议：原名、别名、作品类别、形态、首次日期、简介和搜索补充信息。评级与 AI 字段不由提交者填写。
   */
  newWorkMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pageUrl?: string | null;
  proposedGrade?: ('S' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X') | null;
  /**
   * 第一项作为主规则 / 决定性规则；后续项目保存其他同时命中的规则。它们都只是提交建议。
   */
  matchedRuleCodes?:
    | {
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  claim: string;
  evidenceSummary?: string | null;
  evidenceLinks?:
    | {
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  containsSpoilers?: boolean | null;
  submitter: number | User;
  submitterName?: string | null;
  workflowStatus: 'pending' | 'triaging' | 'needs_information' | 'accepted' | 'rejected' | 'archived';
  reviewer?: (number | null) | User;
  reviewedAt?: string | null;
  reviewNote?: string | null;
  /**
   * 使用本站 Works 主键建立稳定关系，不依赖外部 URL、第三方 ID 或可变 Slug。
   */
  linkedWork?: (number | null) | Work;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules".
 */
export interface Rule {
  id: number;
  title: string;
  slug: string;
  /**
   * 本站内部稳定唯一标识，用于导入、跨来源合并和人工追踪。
   */
  siteId?: string | null;
  category: 'principle' | 'ranking' | 'editorial' | 'migration';
  isLiteVisible?: boolean | null;
  /**
   * 完整版现默认收录全部记录；仅为旧导出器兼容保留。
   */
  isFullVisible?: boolean | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedWarnings?: (number | Warning)[] | null;
  relatedTags?: (number | Tag)[] | null;
  /**
   * 用于导出前台搜索索引的长文本。
   */
  searchText?: string | null;
  legacyXWikiPage?: string | null;
  status: 'draft' | 'review' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'creators';
        value: number | Creator;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'evidence';
        value: number | Evidence;
      } | null)
    | ({
        relationTo: 'stewardship-notices';
        value: number | StewardshipNotice;
      } | null)
    | ({
        relationTo: 'radar-research-records';
        value: number | RadarResearchRecord;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'user-lists';
        value: number | UserList;
      } | null)
    | ({
        relationTo: 'feedback-submissions';
        value: number | FeedbackSubmission;
      } | null)
    | ({
        relationTo: 'terms';
        value: number | Term;
      } | null)
    | ({
        relationTo: 'warnings';
        value: number | Warning;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'rules';
        value: number | Rule;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  accountStatus?: T;
  suspensionReason?: T;
  suspendedAt?: T;
  suspendedBy?: T;
  displayName?: T;
  termsAcceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetCollection?: T;
  targetID?: T;
  targetTitle?: T;
  summary?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaScope?: T;
  originalFilename?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  siteId?: T;
  rank?: T;
  humanAssessment?:
    | T
    | {
        grade?: T;
        status?: T;
        note?: T;
        sourceSummary?: T;
        evidenceStatus?: T;
        sourceLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        assessedAt?: T;
        assessedBy?: T;
      };
  reviewStatus?: T;
  humanReviewNote?: T;
  humanReviewedAt?: T;
  humanReviewedBy?: T;
  importBatch?: T;
  ratingNotice?: T;
  chosenBaseSource?: T;
  reviewReasons?: T;
  sourceConflictNotes?: T;
  evidenceStrength?: T;
  originalTitle?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  localizedTitles?:
    | T
    | {
        title?: T;
        language?: T;
        region?: T;
        kind?: T;
        isPrimary?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  mediaGroup?: T;
  mediaType?: T;
  format?: T;
  firstPublishedAt?: T;
  firstPublishedPrecision?: T;
  firstPublishedLabel?: T;
  externalIds?:
    | T
    | {
        bangumiSubjectId?: T;
        anilistMediaId?: T;
        vndbId?: T;
        wikidataQid?: T;
        malId?: T;
        officialUrl?: T;
      };
  candidateSources?:
    | T
    | {
        source?: T;
        label?: T;
        externalId?: T;
        url?: T;
        fetchedAt?: T;
        note?: T;
        id?: T;
      };
  workGroup?:
    | T
    | {
        key?: T;
        title?: T;
        relation?: T;
        orderLabel?: T;
        source?: T;
        confidence?: T;
        note?: T;
      };
  yuriCandidateScore?: T;
  isLiteVisible?: T;
  isFullVisible?: T;
  hasEvidence?: T;
  riskMatrix?:
    | T
    | {
        maleImpact?: T;
        relationshipClarity?: T;
        endingSafety?: T;
        creatorSpeechRisk?: T;
        note?: T;
      };
  creators?: T;
  creatorCredits?:
    | T
    | {
        creator?: T;
        role?: T;
        originalRole?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  organizations?:
    | T
    | {
        organization?: T;
        role?: T;
        originalRole?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  tags?: T;
  warnings?: T;
  cover?: T;
  summary?: T;
  analysis?: T;
  sourceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  searchText?: T;
  evidenceNote?: T;
  catalogStatus?: T;
  stewardshipNotices?: T;
  radarAssessment?:
    | T
    | {
        confidencePercent?: T;
        evidenceCoveragePercent?: T;
        evidenceStatus?: T;
        sourceSummary?: T;
        sourceCount?: T;
        policyVersion?: T;
        assessmentBatch?: T;
        suggestedGrade?: T;
        decisiveRuleCode?: T;
        decisiveRuleReason?: T;
        matchedRules?:
          | T
          | {
              code?: T;
              grade?: T;
              confidencePercent?: T;
              reason?: T;
              id?: T;
            };
        contradictions?:
          | T
          | {
              value?: T;
              id?: T;
            };
        requiresHumanReview?: T;
        assessedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-public-conclusions_select".
 */
export interface RadarPublicConclusionsSelect<T extends boolean = true> {
  publicationKey?: T;
  work?: T;
  workIdSnapshot?: T;
  workSiteId?: T;
  title?: T;
  recordStatus?: T;
  conclusionMode?: T;
  compatibilityGrade?: T;
  bestGrade?: T;
  likelyGrade?: T;
  worstGrade?: T;
  ratingNotice?: T;
  reviewReasons?: T;
  evidenceStrength?: T;
  radarAssessment?:
    | T
    | {
        confidencePercent?: T;
        evidenceCoveragePercent?: T;
        evidenceStatus?: T;
        sourceSummary?: T;
        sourceCount?: T;
        policyVersion?: T;
        assessmentBatch?: T;
        suggestedGrade?: T;
        decisiveRuleCode?: T;
        decisiveRuleReason?: T;
        matchedRules?:
          | T
          | {
              code?: T;
              grade?: T;
              confidencePercent?: T;
              reason?: T;
              id?: T;
            };
        contradictions?:
          | T
          | {
              value?: T;
              id?: T;
            };
        requiresHumanReview?: T;
        assessedAt?: T;
      };
  sourceKind?: T;
  sourcePackageId?: T;
  sourcePackageSha256?: T;
  conclusionSha256?: T;
  publicationVersion?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-public-records_select".
 */
export interface RadarPublicRecordsSelect<T extends boolean = true> {
  publicationKey?: T;
  work?: T;
  identityKey?: T;
  workIdSnapshot?: T;
  workSiteId?: T;
  title?: T;
  publicState?: T;
  researchStatus?: T;
  pageNotice?: T;
  facts?:
    | T
    | {
        factId?: T;
        factType?: T;
        value?: T;
        sourceRefs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  evidence?:
    | T
    | {
        sourceRef?: T;
        tier?: T;
        role?: T;
        url?: T;
        title?: T;
        exactIdentityBound?: T;
        id?: T;
      };
  sourceReleaseId?: T;
  sourceCommitSha?: T;
  sourcePolicyVersion?: T;
  researchSnapshotId?: T;
  recordSha256?: T;
  releaseRecordsSha256?: T;
  sourceReviewedAt?: T;
  importedAt?: T;
  recordStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-public-ratings_select".
 */
export interface RadarPublicRatingsSelect<T extends boolean = true> {
  publicationKey?: T;
  work?: T;
  identityKey?: T;
  workIdSnapshot?: T;
  workSiteId?: T;
  title?: T;
  coreGrade?: T;
  bestGrade?: T;
  likelyGrade?: T;
  worstGrade?: T;
  confidence?: T;
  matchedClasses?:
    | T
    | {
        value?: T;
        id?: T;
      };
  factRefs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  evidenceRefs?:
    | T
    | {
        value?: T;
        id?: T;
      };
  reasoningSummary?: T;
  unresolvedDimensions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  classificationRule?: T;
  confirmationBasis?:
    | T
    | {
        value?: T;
        id?: T;
      };
  benefitOfDoubtBaselineApplied?: T;
  publicTagHints?:
    | T
    | {
        key?: T;
        group?: T;
        value?: T;
        warningTemplateId?: T;
        id?: T;
      };
  publicWarningTemplateIds?:
    | T
    | {
        value?: T;
        id?: T;
      };
  humanReview?:
    | T
    | {
        status?: T;
        reviewerIdentity?: T;
        reviewedAt?: T;
        decision?: T;
        proposedCoreGrade?: T;
        proposedProfileChanges?:
          | T
          | {
              value?: T;
              id?: T;
            };
        reasoning?: T;
        additionalEvidenceRefs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        moderationState?: T;
        blocksAnalysis?: T;
        blocksPublication?: T;
      };
  sourceReleaseId?: T;
  sourceCommitSha?: T;
  sourcePolicyVersion?: T;
  researchSnapshotId?: T;
  sourceRatingCampaignId?: T;
  sourceRatingDecisionHash?: T;
  releaseRatingHash?: T;
  releaseRatingsSha256?: T;
  importedAt?: T;
  recordStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators_select".
 */
export interface CreatorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteId?: T;
  rank?: T;
  reviewStatus?: T;
  reviewOrigin?: T;
  humanReviewNote?: T;
  humanReviewedAt?: T;
  humanReviewedBy?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  localizedNames?:
    | T
    | {
        name?: T;
        language?: T;
        region?: T;
        kind?: T;
        isPrimary?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  profileImage?: T;
  notes?: T;
  searchText?: T;
  isLiteVisible?: T;
  isFullVisible?: T;
  status?: T;
  stewardshipNotices?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteId?: T;
  type?: T;
  reviewStatus?: T;
  reviewOrigin?: T;
  humanReviewNote?: T;
  humanReviewedAt?: T;
  humanReviewedBy?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  localizedNames?:
    | T
    | {
        name?: T;
        language?: T;
        region?: T;
        kind?: T;
        isPrimary?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  sourceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  searchText?: T;
  isLiteVisible?: T;
  isFullVisible?: T;
  status?: T;
  stewardshipNotices?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence_select".
 */
export interface EvidenceSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  siteId?: T;
  evidenceType?: T;
  reviewStatus?: T;
  evidenceStrength?: T;
  relatedWorks?: T;
  relatedCreators?: T;
  relatedOrganizations?: T;
  image?: T;
  description?: T;
  sourceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  capturedAt?: T;
  isPublic?: T;
  searchText?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stewardship-notices_select".
 */
export interface StewardshipNoticesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  tone?: T;
  severity?: T;
  summary?: T;
  details?: T;
  helpUrl?: T;
  applicableCollections?: T;
  sortOrder?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radar-research-records_select".
 */
export interface RadarResearchRecordsSelect<T extends boolean = true> {
  researchKey?: T;
  title?: T;
  programId?: T;
  importBatch?: T;
  batchId?: T;
  wave?: T;
  lane?: T;
  milestone?: T;
  work?: T;
  workIdSnapshot?: T;
  workSiteId?: T;
  recordShape?: T;
  researchStatus?: T;
  yuriRelevance?: T;
  riskSignals?: T;
  proposedLikelyGrade?: T;
  proposedBestGrade?: T;
  proposedWorstGrade?: T;
  sourceSummary?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        sourceType?: T;
        id?: T;
      };
  unresolvedQuestions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  confidencePercent?: T;
  recommendedNextAction?: T;
  recommendedNextQueue?: T;
  researchNote?: T;
  sourceResponseSha256?: T;
  importedAt?: T;
  recordStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  targetCollection?: T;
  targetSlug?: T;
  targetTitle?: T;
  parentComment?: T;
  replyToName?: T;
  replyToUser?: T;
  author?: T;
  authorName?: T;
  body?: T;
  moderationStatus?: T;
  reportCount?: T;
  reportedBy?: T;
  hiddenReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-lists_select".
 */
export interface UserListsSelect<T extends boolean = true> {
  user?: T;
  workSlug?: T;
  workTitle?: T;
  listStatus?: T;
  note?: T;
  uniqueKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-submissions_select".
 */
export interface FeedbackSubmissionsSelect<T extends boolean = true> {
  feedbackType?: T;
  targetCollection?: T;
  targetSlug?: T;
  targetTitle?: T;
  newWorkMetadata?: T;
  pageUrl?: T;
  proposedGrade?: T;
  matchedRuleCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  claim?: T;
  evidenceSummary?: T;
  evidenceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  containsSpoilers?: T;
  submitter?: T;
  submitterName?: T;
  workflowStatus?: T;
  reviewer?: T;
  reviewedAt?: T;
  reviewNote?: T;
  linkedWork?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteId?: T;
  isLiteVisible?: T;
  isFullVisible?: T;
  definition?: T;
  examples?: T;
  relatedWarnings?: T;
  relatedTerms?: T;
  searchText?: T;
  legacyXWikiPage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warnings_select".
 */
export interface WarningsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteId?: T;
  severity?: T;
  category?: T;
  description?: T;
  relatedTerms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteId?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules_select".
 */
export interface RulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  siteId?: T;
  category?: T;
  isLiteVisible?: T;
  isFullVisible?: T;
  body?: T;
  relatedWarnings?: T;
  relatedTags?: T;
  searchText?: T;
  legacyXWikiPage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}