import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const works = read('src/app/(frontend)/works/page.tsx')
const search = read('src/app/(frontend)/search/search-client.tsx')
const recommendations = read('src/app/(frontend)/_lib/recommendations.ts')
const detailLayout = read('src/app/(frontend)/detail-layout-fixes.css')
const assessmentBadge = read('src/app/(frontend)/_components/AssessmentOriginBadge.tsx')
const searchExport = read('scripts/export/build-lite-search-index.mjs')
const detailExport = read('scripts/export/build-lite-detail-index.mjs')
const searchPipeline = read('scripts/export/build-and-enrich-lite-search-index.mjs')
const detailPipeline = read('scripts/export/build-and-enrich-lite-detail-index.mjs')
const trustCard = read('src/app/(frontend)/_components/WorkAssessmentTrustCard.tsx')
const fullExport = read('scripts/export/build-full-public-index.mjs')

test('works page caches sort, titles and normalized search blobs', () => {
  assert.match(works, /cachedSortedWorks/u)
  assert.match(works, /titleCache/u)
  assert.match(works, /searchBlobCache/u)
  assert.match(works, /workFormatLabels/u)
  assert.match(works, /work-type-chip/u)
  assert.match(works, /name="assessment"/u)
  assert.match(works, /work-card-cover/u)
})

test('client search defers typing and reuses the exported index', () => {
  assert.match(search, /useDeferredValue/u)
  assert.match(search, /cache: 'force-cache'/u)
  assert.match(search, /activeMedia/u)
  assert.match(search, /activeRank/u)
  assert.match(search, /activeAssessment/u)
  assert.match(search, /result-card-cover/u)
})

test('recommendations demote uncertain AI grades and high-risk ranks', () => {
  assert.match(recommendations, /ai_synthesized_pending_review/u)
  assert.match(recommendations, /rank === 'X'/u)
  assert.match(recommendations, /needsHumanReview/u)
  assert.match(recommendations, /confidencePercent/u)
  assert.match(recommendations, /evidenceCoveragePercent/u)
})

test('detail titles wrap in full instead of using an ellipsis', () => {
  const detailHeadingRule = detailLayout.match(/\.detail-hero h1\s*\{(?<body>[^}]*)\}/u)?.groups?.body || ''
  assert.match(detailHeadingRule, /white-space:\s*normal/u)
  assert.match(detailHeadingRule, /overflow-wrap:\s*anywhere/u)
  assert.match(detailHeadingRule, /text-wrap:\s*wrap/u)
  assert.doesNotMatch(detailHeadingRule, /text-wrap:\s*balance/u)
  assert.doesNotMatch(detailHeadingRule, /text-overflow:\s*ellipsis/u)
  assert.doesNotMatch(detailHeadingRule, /white-space:\s*nowrap/u)
  assert.match(detailLayout, /\.detail-hero-layout > div:only-child/u)
  assert.match(detailLayout, /grid-column:\s*1 \/ -1/u)
})

test('AI assessment origin is visible without pretending it is human review', () => {
  assert.match(works, /AssessmentOriginBadge/u)
  assert.match(search, /AssessmentOriginBadge/u)
  assert.match(assessmentBadge, /AI 已评估 · 待人工复核/u)
  assert.match(assessmentBadge, /AI 辅助 · 人工已复核/u)
  assert.doesNotMatch(assessmentBadge, /AI 已人工审核/u)
})

test('complete export is exhaustive, keeps Lite visibility explicit and avoids duplicate full scans', () => {
  assert.match(searchExport, /PUBLIC_INDEX_PAGE_LIMIT \|\| 100/u)
  assert.match(detailExport, /PUBLIC_INDEX_PAGE_LIMIT \|\| 100/u)
  assert.match(searchExport, /profile === 'lite'/u)
  assert.match(detailExport, /profile === 'lite'/u)
  assert.match(searchExport, /retrying \$\{collection\} at depth=0/u)
  assert.match(detailExport, /retrying \$\{collection\} at depth=0/u)
  assert.match(searchExport, /status !== 'archived'/u)
  assert.match(detailExport, /status !== 'archived'/u)
  assert.doesNotMatch(searchExport, /draft=true/u)
  assert.doesNotMatch(detailExport, /draft=true/u)
  assert.doesNotMatch(searchExport, /where\[isFullVisible\]/u)
  assert.doesNotMatch(detailExport, /where\[isFullVisible\]/u)
  assert.match(detailExport, /'organizations', 'evidence'/u)
  assert.match(searchExport, /radarAssessment: normalizeRadarAssessment/u)
  assert.match(detailExport, /radarAssessment: normalizeRadarAssessment/u)
  assert.doesNotMatch(searchPipeline, /enrich-lite-review-fields\.mjs/u)
  assert.doesNotMatch(searchPipeline, /enrich-lite-title-search-fields\.mjs/u)
  assert.doesNotMatch(detailPipeline, /enrich-lite-source-display-fields\.mjs/u)
  assert.doesNotMatch(detailPipeline, /enrich-lite-evidence-details\.mjs/u)
  assert.doesNotMatch(detailPipeline, /enrich-lite-risk-matrix\.mjs/u)
  assert.doesNotMatch(fullExport, /enrich-public-work-status\.mjs/u)
  assert.match(searchExport, /radar-research-records/u)
  assert.match(searchExport, /researchPreview/u)
  assert.match(trustCard, /AI 研究档案 · 非正式评级/u)
  assert.match(trustCard, /不会覆盖 Works 的人工参考轨道/u)
})
