import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const studio = read('src/app/(frontend)/me/studio/page.tsx')
const editor = read('src/app/(frontend)/me/studio/works/[id]/page.tsx')
const create = read('src/app/(frontend)/me/studio/works/new/page.tsx')
const workReviewRoute = read('src/app/(frontend)/me/review/content/works/[id]/page.tsx')
const aiReviewDetail = read('src/app/(frontend)/me/review/content/ai-work-review-detail.tsx')
const account = read('src/app/(frontend)/_components/AccountClient.tsx')
const feedback = read('src/app/(frontend)/me/review/feedback/[id]/page.tsx')
const feedbackActions = read('src/app/(frontend)/me/review/feedback/review-actions.ts')
const feedbackForm = read('src/app/(frontend)/_components/FeedbackForm.tsx')
const pendingButton = read('src/app/(frontend)/me/studio/_components/PendingSubmitButton.tsx')
const sync = read('src/lib/publicIndexSync.ts')
const richText = read('src/lib/richTextPlain.ts')
const guards = read('src/app/(frontend)/_lib/public-entity-guards.ts')
const config = read('payload.config.ts')
const fullExport = read('scripts/export/build-full-public-index.mjs')

function functionBody(source, name, nextName) {
  const start = source.indexOf(`async function ${name}`)
  const end = source.indexOf(`async function ${nextName}`, start + 1)
  assert.notEqual(start, -1, `missing function ${name}`)
  return source.slice(start, end === -1 ? source.length : end)
}

test('content studio is database-backed and separate from review queues', () => {
  assert.match(studio, /collection: 'works'/u)
  assert.match(studio, /draft: false/u)
  assert.match(studio, /搜索数据库/u)
  assert.match(studio, /AI 评级人工复核/u)
  assert.match(studio, /用户提交审核/u)
})

test('Studio distinguishes formal, temporary and archived works', () => {
  assert.match(studio, /type StudioStatus = 'active' \| 'temporary' \| 'archived' \| 'all'/u)
  assert.match(studio, /正式作品/u)
  assert.match(studio, /临时作品/u)
  assert.match(studio, /回收站/u)
  assert.match(studio, /catalogStatus: 'temporary'/u)
  assert.match(studio, /恢复为临时作品/u)
  assert.doesNotMatch(studio, /恢复为待复核草稿/u)

  const pageQuery = functionBody(studio, 'findStudioPage', 'countByStatus')
  assert.match(pageQuery, /draft: false/u)
  assert.doesNotMatch(pageQuery, /draft: true/u)
})

test('members submit proposals while staff can edit live works', () => {
  assert.match(studio, /import \{ isEditor \} from '@\/access\/roles'/u)
  assert.match(studio, /if \(!canEdit\(auth\.user\)\)/u)
  assert.doesNotMatch(studio, /roleOf|staffRoles/u)
  assert.match(studio, /普通用户填写的新作品仍是待审核申请/u)
  assert.match(studio, /\/feedback\?type=new_work/u)
  assert.match(account, /href="\/me\/studio"/u)
  assert.match(editor, /没有作品编辑权限/u)
})

test('staff creation produces a published temporary work and links feedback with numeric IDs', () => {
  assert.match(create, /_status: 'published'/u)
  assert.match(create, /catalogStatus: 'temporary'/u)
  assert.match(create, /reviewStatus: 'pending'/u)
  assert.match(create, /isLiteVisible: true/u)
  assert.match(create, /isFullVisible: true/u)
  assert.match(create, /const actorID = numericID/u)
  assert.match(create, /const createdID = numericID\(created\.id\)/u)
  assert.match(create, /linkedWork: createdID/u)
  assert.match(create, /reviewer: actorID/u)
  assert.match(feedbackActions, /catalogStatus: 'temporary'/u)
  assert.match(feedbackActions, /_status: 'published'/u)
})

test('temporary work creation returns to its parent with visible success and double-submit protection', () => {
  assert.match(create, /withCreatedWork\(returnTo, createdID\)/u)
  assert.match(create, /name="returnTo"/u)
  assert.match(create, /PendingSubmitButton/u)
  assert.match(pendingButton, /useFormStatus/u)
  assert.match(pendingButton, /disabled=\{pending\}/u)
  assert.match(studio, /const createdWork = first\(raw\.createdWork\)/u)
  assert.match(studio, /临时作品 #\{createdWork\} 已创建并公开/u)
  assert.match(create, /创建并公开临时作品/u)
  assert.match(feedbackForm, /router\.back\(\)/u)
  assert.match(feedbackForm, /返回上一级/u)
})

test('member new-work metadata is transferred into the accepted temporary work', () => {
  assert.match(feedbackForm, /newWorkOriginalTitle/u)
  assert.match(feedbackForm, /newWorkAliases/u)
  assert.match(feedbackForm, /newWorkMediaGroup/u)
  assert.match(feedbackForm, /newWorkFirstPublishedAt/u)
  assert.match(feedbackForm, /newWorkSummary/u)
  assert.match(feedbackForm, /newWorkSearchText/u)
  assert.match(feedback, /用户提交的新作品建档资料/u)
  assert.match(feedbackActions, /newWorkProposalToWorkTransfer/u)
  assert.match(feedbackActions, /\.\.\.transfer\.workData/u)
  assert.match(feedbackActions, /plainTextToRichText\(transfer\.summaryText\)/u)
  assert.match(feedbackActions, /linkedWork: createdID/u)
  assert.match(feedbackForm, /proposedGrade: isNewWork \? undefined/u)
  assert.match(feedbackForm, /matchedRuleCodes: isNewWork \? \[\]/u)
})

test('manual creation leaves AI empty for the next unassessed pipeline', () => {
  assert.match(create, /rank: 'unknown'/u)
  assert.match(create, /ratingNotice: 'none'/u)
  assert.match(create, /AI Radar 等待区/u)
  assert.match(create, /radar:local-update --scope unassessed/u)
  assert.doesNotMatch(create, /RadarRuleSelector/u)
  assert.doesNotMatch(create, /RADAR_RATING_POLICY_ID/u)
  assert.doesNotMatch(create, /radarAssessment:/u)
  assert.doesNotMatch(create, /suggestedGrade|decisiveRuleCode|matchedRules/u)
})

test('work review route opens the AI-rated human review page', () => {
  assert.match(workReviewRoute, /AIWorkReviewDetail/u)
  assert.doesNotMatch(workReviewRoute, /\/me\/studio\/works\//u)
  assert.match(aiReviewDetail, /AI 评级人工复核/u)
  assert.match(aiReviewDetail, /已有受控 AI 评级、尚无人工评级/u)
  assert.match(aiReviewDetail, /展开作品前台实时预览/u)
  assert.match(aiReviewDetail, /只保存人工复核记录/u)
  assert.match(aiReviewDetail, /确认人工评级并通过/u)
  assert.match(aiReviewDetail, /驳回 AI 建议并标记争议/u)
})

test('work introduction remains editable while AI fields are pipeline-owned', () => {
  assert.match(editor, /name="summary"/u)
  assert.match(editor, /作品简介（面向读者）/u)
  assert.match(editor, /data\.summary = plainTextToRichText/u)
  assert.match(create, /name="summary"/u)
  assert.match(create, /plainTextToRichText\(summary\)/u)
  assert.match(richText, /richTextToPlainText/u)
  assert.match(richText, /plainTextToRichText/u)
  assert.match(config, /flags\.firstPartyStudio/u)
  assert.match(config, /radar\.assessedAt/u)
})

test('soft hide archives a work and restore returns it as a published temporary work', () => {
  assert.match(studio, /catalogStatus: 'archived'/u)
  assert.match(studio, /_status: 'draft'/u)
  assert.match(studio, /isLiteVisible: false/u)
  assert.match(studio, /isFullVisible: false/u)
  assert.match(studio, /catalogStatus: 'temporary'/u)
  assert.match(studio, /_status: 'published'/u)
  assert.match(studio, /isLiteVisible: true/u)
  assert.match(studio, /isFullVisible: true/u)
  assert.match(studio, /First-party studio soft hide failed/u)
  assert.doesNotMatch(studio, /payload\.delete/u)
  assert.doesNotMatch(studio, /DELETE FROM/u)
})

test('studio edits synchronize public indexes and remove only hidden records', () => {
  assert.match(editor, /syncWorkToPublicIndexes/u)
  assert.match(config, /context\?\.firstPartyStudio/u)
  assert.match(sync, /search-index\.json/u)
  assert.match(sync, /detail-index\.json/u)
  assert.match(sync, /status: text\(work\._status\)/u)
  assert.match(sync, /catalogStatus: text\(work\.catalogStatus\)/u)
  assert.match(sync, /reviewReasonValues/u)
  assert.match(sync, /detailSections/u)
  assert.match(sync, /radarAssessment: work\.radarAssessment/u)
  assert.match(sync, /richTextToPlainText\(work\.summary\)/u)
  assert.match(sync, /shouldRemoveFromPublicIndexes/u)
  assert.match(sync, /work\.catalogStatus === 'archived'/u)
  assert.match(sync, /index\.items\.splice\(position, 1\)/u)
  assert.match(guards, /item\.catalogStatus === 'archived'/u)
  assert.match(fullExport, /build-and-enrich-lite-search-index\.mjs/u)
  assert.match(fullExport, /build-and-enrich-lite-detail-index\.mjs/u)
})

test('studio remains Payload-only and never writes PostgreSQL directly', () => {
  for (const source of [studio, editor, create, sync, feedbackActions]) {
    assert.doesNotMatch(source, /pg_query|psql|ALTER TABLE|UPDATE works SET|DELETE FROM works/iu)
  }
})
