import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const collection = read('src/collections/FeedbackSubmissions.ts')
const form = read('src/app/(frontend)/_components/FeedbackForm.tsx')
const prompt = read('src/app/(frontend)/_components/FeedbackPrompt.tsx')
const submissions = read('src/app/(frontend)/me/submissions/page.tsx')
const submissionEditor = read('src/app/(frontend)/me/submissions/[id]/page.tsx')
const proposal = read('src/lib/newWorkProposal.ts')
const migration = read('scripts/migrations/20260720-add-feedback-new-work-metadata.sql')
const versionEnumMigration = read('scripts/migrations/20260721-add-temporary-to-work-version-enum.sql')
const config = read('payload.config.ts')

test('feedback collection is registered with a moderated workflow', () => {
  assert.match(config, /FeedbackSubmissions/u)
  assert.match(collection, /slug: 'feedback-submissions'/u)
  assert.match(collection, /create: signedIn/u)
  assert.match(collection, /workflowStatus: 'pending'/u)
  assert.match(collection, /value: 'accepted'/u)
  assert.match(collection, /value: 'rejected'/u)
})

test('human radar material keeps grade, rules, sources and spoiler state', () => {
  assert.match(collection, /name: 'proposedGrade'/u)
  assert.match(collection, /name: 'matchedRuleCodes'/u)
  assert.match(collection, /name: 'evidenceLinks'/u)
  assert.match(collection, /name: 'containsSpoilers'/u)
  assert.match(form, /proposedGrade/u)
  assert.match(form, /matchedRuleCodes/u)
  assert.match(form, /提交给人工审核/u)
})

test('new work proposals keep catalog metadata but exclude member-authored AI assessment fields', () => {
  assert.match(collection, /name: 'newWorkMetadata'/u)
  assert.match(collection, /type: 'json'/u)
  assert.match(collection, /sanitizeNewWorkProposalMetadata/u)
  assert.match(collection, /next\.proposedGrade = null/u)
  assert.match(collection, /next\.matchedRuleCodes = \[\]/u)
  assert.match(form, /newWorkOriginalTitle/u)
  assert.match(form, /newWorkAliases/u)
  assert.match(form, /newWorkMediaGroup/u)
  assert.match(form, /newWorkFirstPublishedAt/u)
  assert.match(form, /newWorkSummary/u)
  assert.match(form, /newWorkSearchText/u)
  assert.match(form, /proposedGrade: isNewWork \? undefined/u)
  assert.match(form, /matchedRuleCodes: isNewWork \? \[\]/u)
  assert.match(proposal, /NewWorkProposalMetadata/u)
  assert.match(proposal, /sanitizeNewWorkProposalMetadata/u)
})

test('accepted new-work submissions keep every factual field in a public temporary work', () => {
  assert.match(collection, /linkedWorkID !== previousLinkedWorkID/u)
  assert.match(collection, /directIntakeWork/u)
  assert.match(collection, /newWorkProposalToWorkTransfer/u)
  assert.match(collection, /feedbackMetadataTransfer: true/u)
  assert.match(collection, /plainTextToRichText\(transfer\.summaryText\)/u)
  assert.match(collection, /_status: 'published'/u)
  assert.match(collection, /catalogStatus: 'temporary'/u)
  assert.match(collection, /isLiteVisible: true/u)
  assert.match(collection, /isFullVisible: true/u)
  assert.match(proposal, /originalTitle/u)
  assert.match(proposal, /aliases: \(metadata\.aliases \|\| \[\]\)\.map/u)
  assert.match(proposal, /localizedTitles/u)
  assert.match(proposal, /mediaGroup: metadata\.mediaGroup \|\| 'unknown'/u)
  assert.match(proposal, /mediaType: metadata\.mediaType \|\| 'unknown'/u)
  assert.match(proposal, /format: metadata\.format \|\| 'unknown'/u)
  assert.match(proposal, /firstPublishedAt: metadata\.firstPublishedAt \|\| null/u)
  assert.match(proposal, /firstPublishedPrecision: metadata\.firstPublishedPrecision \|\| 'unknown'/u)
  assert.match(proposal, /firstPublishedLabel: metadata\.firstPublishedLabel \|\| ''/u)
  assert.doesNotMatch(proposal, /radarAssessment|humanAssessment/u)
})

test('structured proposal storage is an additive nullable JSONB migration', () => {
  assert.match(migration, /ADD COLUMN IF NOT EXISTS "new_work_metadata" jsonb/u)
  assert.match(migration, /BEGIN;/u)
  assert.match(migration, /COMMIT;/u)
  assert.doesNotMatch(migration, /DROP TABLE|DROP COLUMN|DELETE FROM|UPDATE /iu)
})

test('temporary lifecycle value is added to the separate Works version enum', () => {
  assert.match(versionEnumMigration, /_works_v/u)
  assert.match(versionEnumMigration, /version_catalog_status/u)
  assert.match(versionEnumMigration, /ALTER TYPE %I ADD VALUE IF NOT EXISTS %L/u)
  assert.match(versionEnumMigration, /temporary/u)
  assert.doesNotMatch(versionEnumMigration, /DROP TABLE|DROP COLUMN|DELETE FROM|UPDATE /iu)
})

test('detail feedback prompt routes into the internal form', () => {
  assert.match(prompt, /feedbackPageUrl/u)
  assert.match(prompt, /\/feedback\?/u)
  assert.match(prompt, /params\.set\('workId', item\.recordId\)/u)
  assert.doesNotMatch(prompt, /params\.set\('workId', item\.id\)/u)
  assert.match(form, /站内作品 ID/u)
  assert.doesNotMatch(form, /type="url"/u)
  assert.match(collection, /label: '关联站内作品 ID'/u)
  assert.match(form, /linkedWork: workID \? Number\(workID\) : undefined/u)
  assert.match(collection, /name: 'pageUrl'.*hidden: true/u)
  assert.doesNotMatch(prompt, /github\.com\/wtyliangtingRe\/baihepailei\/issues\/new/u)
})

test('proposal transfer never writes member-authored ratings or AI conclusions', () => {
  assert.match(collection, /collection: 'works'/u)
  assert.match(collection, /req\.payload\.update/u)
  assert.doesNotMatch(collection, /workData\.radarAssessment|workData\.humanAssessment|workData\.suggestedGrade/u)
})

test('members edit the same open submission with every original field prefilled', () => {
  assert.match(collection, /ownEditableSubmissionOrStaff/u)
  assert.match(collection, /in: \['pending', 'needs_information'\]/u)
  assert.match(collection, /previousStatus === 'needs_information' \? 'pending' : previousStatus/u)
  assert.match(collection, /feedbackType: originalDoc\?\.feedbackType/u)
  assert.match(collection, /linkedWork: originalDoc\?\.linkedWork/u)
  assert.match(collection, /update: ownEditableSubmissionOrStaff/u)
  assert.match(submissions, /提交记录与补充材料/u)
  assert.match(submissions, /补充材料并重新提交/u)
  assert.match(submissionEditor, /FeedbackForm/u)
  assert.match(submissionEditor, /newWorkMetadata: submission\.newWorkMetadata/u)
  assert.match(submissionEditor, /reviewNote: submission\.reviewNote/u)
  assert.match(form, /method: isEditing \? 'PATCH' : 'POST'/u)
  assert.match(form, /initialMetadata\.originalTitle/u)
  assert.match(form, /initialMetadata\.aliases/u)
  assert.match(form, /initialMetadata\.summary/u)
  assert.match(form, /sourceLinksToLines/u)
  assert.match(form, /保存修改并重新提交/u)
})
