import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const users = read('src/collections/Users.ts')
const roles = read('src/access/roles.ts')
const actions = read('src/app/(frontend)/_actions/account.ts')
const session = read('src/app/(frontend)/api/account/session/route.ts')
const personnelRoute = read('src/app/(frontend)/api/personnel/users/[id]/route.ts')
const auth = read('src/app/(frontend)/_components/AuthPanel.tsx')
const account = read('src/app/(frontend)/_components/AccountClient.tsx')
const messages = read('src/app/(frontend)/me/messages/page.tsx')
const submissions = read('src/app/(frontend)/me/submissions/page.tsx')
const submissionEditor = read('src/app/(frontend)/me/submissions/[id]/page.tsx')
const personnel = read('src/app/(frontend)/_components/PersonnelClient.tsx')
const locked = read('src/app/(frontend)/account/locked/page.tsx')
const layout = read('src/app/(frontend)/layout.tsx')
const config = read('payload.config.ts')
const env = read('.env.example')

test('public registration is forced to member and staff admin access is separate', () => {
  assert.match(users, /create: anyone/u)
  assert.match(users, /admin: \(\{ req \}\) => isEditor\(req\.user\)/u)
  assert.match(users, /role: 'member'/u)
  assert.match(users, /SITE_OWNER_EMAIL/u)
  assert.match(users, /isConfiguredOwnerEmail/u)
  assert.match(users, /beforeLogin:/u)
  assert.match(users, /overrideAccess: true/u)
  assert.match(users, /verificationNeedsNormalization/u)
  assert.match(users, /_verified: true/u)
  assert.match(users, /注册时必须填写显示名/u)
  assert.match(users, /value: 'owner'/u)
  assert.match(users, /value: 'admin'/u)
  assert.match(users, /value: 'editor'/u)
  assert.match(users, /value: 'member'/u)
  assert.match(users, /name: 'accountStatus'/u)
  assert.match(users, /value: 'suspended'/u)
})

test('role hierarchy grants internal capability only to owner, admin and editor', () => {
  assert.match(roles, /'owner' \| 'admin' \| 'editor'/u)
  assert.match(roles, /isConfiguredOwner/u)
  assert.match(roles, /SITE_OWNER_EMAIL/u)
  assert.match(roles, /role === 'owner'/u)
  assert.doesNotMatch(roles, /role === 'reviewer'|role === 'trusted'/u)
})

test('auth flow supports verification, login, logout and email password reset', () => {
  assert.match(users, /verify:/u)
  assert.match(users, /ACCOUNT_EMAIL_VERIFICATION_ENABLED/u)
  assert.match(users, /forgotPassword:/u)
  assert.match(actions, /@payloadcms\/next\/auth/u)
  assert.match(actions, /logout\(/u)
  assert.match(session, /generatePayloadCookie/u)
  assert.match(session, /maxAge: authConfig\.tokenExpiration/u)
  assert.match(session, /path: '\/'/u)
  assert.match(session, /payload\.auth/u)
  assert.match(session, /getRole\(user\)/u)
  assert.match(session, /account_suspended/u)
  assert.match(auth, /\/account\/locked/u)
  assert.match(auth, /\/api\/account\/session/u)
  assert.doesNotMatch(auth, /\/api\/users\/login/u)
  assert.match(auth, /\/api\/users\/forgot-password/u)
  assert.match(auth, /\/api\/users\/reset-password/u)
  assert.match(auth, /\/api\/users\/verify\//u)
  assert.match(account, /logoutAccount/u)
  assert.match(account, /\/api\/account\/session/u)
  assert.doesNotMatch(account, /\/api\/users\/logout/u)
  assert.match(config, /nodemailerAdapter/u)
  assert.match(config, /smtp\.example\.com/u)
  assert.match(env, /SMTP_HOST/u)
  assert.match(env, /ACCOUNT_EMAIL_VERIFICATION_ENABLED=false/u)
})

test('frontend consolidates submissions under account and exposes the message center', () => {
  assert.match(layout, /href: '\/account', label: '账户'/u)
  assert.doesNotMatch(layout, /href: '\/admin', label: '后台'/u)
  assert.doesNotMatch(layout, /href: '\/feedback', label: '反馈'/u)
  assert.match(account, /我的列表/u)
  assert.match(account, /提交人工排雷/u)
  assert.match(account, /href="\/me\/messages"/u)
  assert.match(account, /href="\/me\/submissions"/u)
  assert.match(account, /站务消息/u)
  assert.match(account, /我的提交/u)
  assert.match(account, /\/me\/personnel/u)
  assert.match(messages, /消息与提醒/u)
  assert.match(messages, /feedback-submissions/u)
  assert.match(messages, /parentComment/u)
  assert.match(messages, /站务需要你补充材料/u)
  assert.match(messages, /`\/me\/submissions\/\$\{feedback\.id\}`/u)
  assert.match(messages, /回复了你在《/u)
  assert.match(submissions, /提交记录与补充材料/u)
  assert.match(submissions, /workflowStatus/u)
  assert.match(submissions, /补充材料并重新提交/u)
  assert.match(submissionEditor, /编辑原记录/u)
  assert.match(submissionEditor, /relationID\(submission\.submitter\) !== String\(userID\)/u)
  assert.match(personnel, /人员任命与账号封停/u)
  assert.match(personnel, /保存任命/u)
  assert.match(personnel, /封停账号/u)
  assert.match(locked, /此账户已被封停/u)
})

test('personnel writes use a same-origin route with an explicit field and hierarchy boundary', () => {
  assert.match(personnel, /\/api\/personnel\/users\//u)
  assert.doesNotMatch(personnel, /method: 'PATCH'[\s\S]{0,220}\/api\/users\//u)
  assert.match(personnelRoute, /isSameOrigin\(request\)/u)
  assert.match(personnelRoute, /payload\.auth\(\{ headers: request\.headers \}\)/u)
  assert.match(personnelRoute, /actorRole !== 'owner' && actorRole !== 'admin'/u)
  assert.match(personnelRoute, /ownerAssignableRoles/u)
  assert.match(personnelRoute, /adminAssignableRoles/u)
  assert.match(personnelRoute, /Object\.keys\(data\)\.length === 0/u)
  assert.match(personnelRoute, /overrideAccess: true/u)
  assert.match(personnelRoute, /personnelManagement: true/u)
  assert.match(personnelRoute, /user: authUser/u)
})

test('account suspension is audited, revokes sessions and gives a visible reason requirement', () => {
  assert.match(users, /new APIError\('此账户已被封停。'/u)
  assert.match(users, /sessions: newlySuspended \? \[\]/u)
  assert.match(users, /suspendedAt:/u)
  assert.match(users, /suspendedBy:/u)
  assert.match(users, /actorRole === 'owner'/u)
  assert.match(users, /actorRole === 'admin'/u)
  assert.match(users, /original\.role === 'admin'/u)
  assert.match(users, /editingSelf \? \{\} : \{ displayName: original\.displayName, password: undefined \}/u)
  assert.match(personnel, /请先为 \$\{target\.email \|\| target\.id\} 填写封停原因/u)
  assert.match(personnel, /封停后会立即清除该账户现有登录会话/u)
  assert.doesNotMatch(personnel, /disabled=\{!statusManageable \|\| busy \|\| !\(reasons\[target\.id\]/u)
  assert.match(personnel, /assignableByOwner/u)
  assert.match(personnel, /assignableByAdmin/u)
  assert.match(personnel, /target\.role !== 'admin'/u)
})
