import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const users = read('src/collections/Users.ts')
const roles = read('src/access/roles.ts')
const actions = read('src/app/(frontend)/_actions/account.ts')
const session = read('src/app/(frontend)/api/account/session/route.ts')
const auth = read('src/app/(frontend)/_components/AuthPanel.tsx')
const account = read('src/app/(frontend)/_components/AccountClient.tsx')
const personnel = read('src/app/(frontend)/_components/PersonnelClient.tsx')
const locked = read('src/app/(frontend)/account/locked/page.tsx')
const layout = read('src/app/(frontend)/layout.tsx')
const config = read('payload.config.ts')
const env = read('.env.example')

test('public registration is forced to member and staff admin access is separate', () => {
  assert.match(users, /create: anyone/u)
  assert.match(users, /admin: \(\{ req \}\) => isEditor\(req\.user\)/u)
  assert.match(users, /role: 'member'/u)
  assert.match(users, /SITE_OWNER_EMAIL/u)
  assert.match(users, /isConfiguredOwnerEmail/u)
  assert.match(users, /beforeLogin:/u)
  assert.match(users, /overrideAccess: true/u)
  assert.match(users, /verificationNeedsNormalization/u)
  assert.match(users, /_verified: true/u)
  assert.match(users, /注册时必须填写显示名/u)
  assert.match(users, /value: 'owner'/u)
  assert.match(users, /value: 'admin'/u)
  assert.match(users, /value: 'editor'/u)
  assert.match(users, /value: 'member'/u)
  assert.match(users, /name: 'accountStatus'/u)
  assert.match(users, /value: 'suspended'/u)
})

test('role hierarchy grants internal capability only to owner, admin and editor', () => {
  assert.match(roles, /'owner' \| 'admin' \| 'editor'/u)
  assert.match(roles, /role === 'owner'/u)
  assert.doesNotMatch(roles, /role === 'reviewer'|role === 'trusted'/u)
})

test('auth flow supports verification, login, logout and email password reset', () => {
  assert.match(users, /verify:/u)
  assert.match(users, /ACCOUNT_EMAIL_VERIFICATION_ENABLED/u)
  assert.match(users, /forgotPassword:/u)
  assert.match(actions, /@payloadcms\/next\/auth/u)
  assert.match(actions, /logout\(/u)
  assert.match(session, /generatePayloadCookie/u)
  assert.match(session, /maxAge: authConfig\.tokenExpiration/u)
  assert.match(session, /path: '\/'/u)
  assert.match(session, /payload\.auth/u)
  assert.match(session, /account_suspended/u)
  assert.match(auth, /\/account\/locked/u)
  assert.match(auth, /\/api\/account\/session/u)
  assert.doesNotMatch(auth, /\/api\/users\/login/u)
  assert.match(auth, /\/api\/users\/forgot-password/u)
  assert.match(auth, /\/api\/users\/reset-password/u)
  assert.match(auth, /\/api\/users\/verify\//u)
  assert.match(account, /logoutAccount/u)
  assert.match(account, /\/api\/account\/session/u)
  assert.doesNotMatch(account, /\/api\/users\/logout/u)
  assert.match(config, /nodemailerAdapter/u)
  assert.match(config, /smtp\.example\.com/u)
  assert.match(env, /SMTP_HOST/u)
  assert.match(env, /ACCOUNT_EMAIL_VERIFICATION_ENABLED=false/u)
})

test('frontend exposes an account entry instead of a public admin entry', () => {
  assert.match(layout, /href: '\/account', label: '账户'/u)
  assert.doesNotMatch(layout, /href: '\/admin', label: '后台'/u)
  assert.match(account, /我的列表/u)
  assert.match(account, /提交人工排雷/u)
  assert.match(account, /\/me\/personnel/u)
  assert.match(personnel, /人员任命与账号封停/u)
  assert.match(personnel, /保存任命/u)
  assert.match(personnel, /封停账号/u)
  assert.match(locked, /此账户已被封停/u)
})

test('account suspension is audited, revokes sessions and respects hierarchy', () => {
  assert.match(users, /new APIError\('此账户已被封停。'/u)
  assert.match(users, /sessions: newlySuspended \? \[\]/u)
  assert.match(users, /suspendedAt:/u)
  assert.match(users, /suspendedBy:/u)
  assert.match(users, /actorRole === 'owner'/u)
  assert.match(users, /actorRole === 'admin'/u)
  assert.match(users, /original\.role === 'admin'/u)
  assert.match(users, /editingSelf \? \{\} : \{ displayName: original\.displayName, password: undefined \}/u)
  assert.match(personnel, /assignableByOwner/u)
  assert.match(personnel, /assignableByAdmin/u)
  assert.match(personnel, /target\.role !== 'admin'/u)
})
