import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { execFileSync, spawnSync } from 'node:child_process'
import { archiveInventory, assertRelative, jsonl, loadResearchPackage, normalizeContentProfile, sha256File, sha256Text, validateOutcome } from '../scripts/radar/lib/research-assessment-handoff-v02.mjs'
const repo=path.resolve('.'); const assembler=path.join(repo,'scripts/radar/assemble-radar-research-assessment-bulk-v02.mjs')
function fixture(){ const root=fs.mkdtempSync(path.join(os.tmpdir(),'radar-v02-')); const rows=[
 {workId:'1',siteId:'w:1',title:'one',researchDisposition:'ready_for_ai_assessment',allowedAssessmentModes:['exact','bounded_range'],identity:{identityStatus:'confirmed'},writeProtection:{protected:false,reasons:[]},research:{sources:[{url:'https://e/1'}]},contentProfile:{sexualContent:'unknown'},riskLabels:['sexual_content:unknown'],requiresHumanReview:true,publicationEligible:false,pageNotice:'AI 综合，待复核'},
 {workId:'2',siteId:'w:2',title:'two',researchDisposition:'needs_more_research',allowedAssessmentModes:['bounded_range','labels_only'],identity:{identityStatus:'confirmed'},writeProtection:{protected:true,reasons:['review']},research:{sources:[]},contentProfile:{sexualContent:'none_found'},riskLabels:['sexual_content:none_found'],requiresHumanReview:true,publicationEligible:false,pageNotice:'AI 综合，待复核'},
 {workId:'3',siteId:'w:3',title:'three',researchDisposition:'identity_review',allowedAssessmentModes:['labels_only'],identity:{identityStatus:'ambiguous'},writeProtection:{protected:true,reasons:['identity']},research:{sources:[]},contentProfile:{sexualContent:'unknown'},riskLabels:['sexual_content:unknown'],requiresHumanReview:true,publicationEligible:false,pageNotice:'AI 综合，待复核'}]
 const input='handoffs/wave-01/inputs/wave-01-chunk-01.input.jsonl', response='handoffs/wave-01/responses/wave-01-chunk-01.output.jsonl', immutable='handoffs/wave-01/immutable-input-v02.jsonl'; for(const rel of [input,response,immutable]) fs.mkdirSync(path.dirname(path.join(root,rel)),{recursive:true}); fs.writeFileSync(path.join(root,input),jsonl(rows)); fs.writeFileSync(path.join(root,immutable),jsonl(rows)); const outcomes=[{assessmentMode:'exact',exactGradeSuggestion:'A',gradeRange:null},{assessmentMode:'bounded_range',exactGradeSuggestion:null,gradeRange:{best:'A',likely:'C',worst:'F'}},{assessmentMode:'labels_only',exactGradeSuggestion:null,gradeRange:null}]; const responses=rows.map((row,i)=>({...row,...outcomes[i],ruleAssessments:[],syntheticRehearsal:true})); fs.writeFileSync(path.join(root,response),jsonl(responses)); const wave={version:'ai-radar-research-assessment-handoff-v0.2',wave:'wave-01',rowCount:3,immutableInputFile:immutable,immutableInputSha256:sha256File(path.join(root,immutable)),chunks:[{chunkId:'wave-01-chunk-01',rowCount:3,inputFile:input,inputSha256:sha256File(path.join(root,input)),responseFile:response}]}; const waveFile='handoffs/wave-01/wave-manifest-v02.json'; fs.writeFileSync(path.join(root,waveFile),JSON.stringify(wave)); const manifest={version:wave.version,inputRows:3,waves:[{...wave,manifestFile:waveFile,manifestSha256:sha256File(path.join(root,waveFile))}],safety:{payloadWrite:false,directPostgresqlWrite:false,modifiesWorks:false,publishesRatings:false,productionApplyAuthorized:false}}; fs.writeFileSync(path.join(root,'package-manifest.json'),JSON.stringify(manifest)); return {root,rows,responses,response:path.join(root,response)} }
function run(root,synthetic=false){ return spawnSync(process.execPath,[assembler,'--package-dir',root,...(synthetic?['--synthetic-rehearsal']:[])],{encoding:'utf8'}) }
test('mode contract, range order, and automatic X rejection',()=>{ assert.doesNotThrow(()=>validateOutcome({assessmentMode:'exact',exactGradeSuggestion:'A',gradeRange:null,riskLabels:[],ruleAssessments:[],requiresHumanReview:true,publicationEligible:false},'ready_for_ai_assessment')); assert.doesNotThrow(()=>validateOutcome({assessmentMode:'labels_only',exactGradeSuggestion:null,gradeRange:null,riskLabels:[],ruleAssessments:[],requiresHumanReview:true,publicationEligible:false},'identity_review')); assert.throws(()=>validateOutcome({assessmentMode:'bounded_range',exactGradeSuggestion:null,gradeRange:{best:'D',likely:'A',worst:'F'},riskLabels:[],ruleAssessments:[],requiresHumanReview:true,publicationEligible:false},'needs_more_research')); assert.throws(()=>validateOutcome({assessmentMode:'exact',exactGradeSuggestion:'X',gradeRange:null,riskLabels:[],ruleAssessments:[],requiresHumanReview:true,publicationEligible:false},'ready_for_ai_assessment')); assert.throws(()=>validateOutcome({assessmentMode:'bounded_range',exactGradeSuggestion:null,gradeRange:{best:'A',likely:'F',worst:'X'},riskLabels:[],ruleAssessments:[],requiresHumanReview:true,publicationEligible:false},'ready_for_ai_assessment')) })
test('content normalization keeps factual dimensions separate and participants unknown',()=>{ const p=normalizeContentProfile({riskFindings:{adultContent:'explicit',maleInvolvement:'none_found',ntrRisk:'possible',violenceOrHorror:'severe',ageOrConsentRisk:'possible',coercionRisk:'confirmed',settingProfiles:['TS','futa','ABO','otokonoko']}}); assert.equal(p.sexualParticipants,'unknown'); assert.deepEqual([p.ts,p.futa,p.abo,p.crossdressingOrOtokonoko],[true,true,true,true]); assert.equal(p.ntrRisk,'possible'); assert.equal(p.maleInvolvement,'none_found'); assert.equal(p.violenceOrHorror,'severe'); assert.equal(p.ageOrConsentRisk,'possible'); assert.equal(p.coercionRisk,'confirmed'); assert.equal(normalizeContentProfile({riskFindings:{adultContent:'none_found',violenceOrHorror:'severe'}}).sexualParticipants,'none') })
test('path confinement rejects traversal and absolute paths',()=>{ for(const value of ['../x','/x','C:\\x']) assert.throws(()=>assertRelative(value)) })
test('synthetic fixture validates all modes but is never genuine assessment evidence',()=>{ const f=fixture(); const result=run(f.root,true); assert.equal(result.status,0,result.stderr); const s=JSON.parse(result.stdout); assert.equal(s.genuineAssessmentComplete,false); assert.equal(s.syntheticValidationComplete,true); assert.equal(s.syntheticAssembledRows,3); assert.equal(s.assembledRows,0); assert.ok(s.blockers.includes('synthetic_response_not_real_assessment')) })
test('synthetic responses are forbidden outside explicit synthetic mode',()=>{ const f=fixture(); const result=run(f.root,false); assert.equal(result.status,2); assert.match(result.stdout,/synthetic_response_forbidden/u) })
test('missing response is blocked and never assembled',()=>{ const f=fixture(); fs.rmSync(f.response); const result=run(f.root); assert.equal(result.status,2); assert.match(result.stdout,/response_missing/u) })
test('duplicate and count-mismatched responses are blocked',()=>{ const f=fixture(); fs.writeFileSync(f.response,jsonl([f.responses[0],f.responses[0],f.responses[2],f.responses[2]])); const result=run(f.root,true); assert.equal(result.status,2); assert.match(result.stdout,/response_count_mismatch|duplicate_response_identity/u) })
test('reordered response identity/order is blocked',()=>{ const f=fixture(); fs.writeFileSync(f.response,jsonl([f.responses[1],f.responses[0],f.responses[2]])); const result=run(f.root,true); assert.equal(result.status,2); assert.match(result.stdout,/workId_or_order_mismatch/u) })
test('input-owned identity, protection, research, profile, and labels rewrites are blocked',()=>{ for(const key of ['identity','writeProtection','research','contentProfile','riskLabels']) { const f=fixture(); const rows=structuredClone(f.responses); rows[0][key]=key==='riskLabels'?['rewritten']:{rewritten:true}; fs.writeFileSync(f.response,jsonl(rows)); const result=run(f.root,true); assert.equal(result.status,2); assert.match(result.stdout,new RegExp(`input_owned_${key}_rewrite`)) } })
test('title and disposition rewrites are blocked',()=>{ for(const key of ['title','researchDisposition']) { const f=fixture(); const rows=structuredClone(f.responses); rows[0][key]='rewritten'; fs.writeFileSync(f.response,jsonl(rows)); const result=run(f.root,true); assert.equal(result.status,2); assert.match(result.stdout,new RegExp(`${key}_or_order_mismatch`)) } })
test('tampered wave manifest hash is blocked',()=>{ const f=fixture(); const file=path.join(f.root,'handoffs/wave-01/wave-manifest-v02.json'); fs.appendFileSync(file,' '); const result=run(f.root,true); assert.equal(result.status,2); assert.match(result.stdout,/wave_manifest_sha_mismatch/u) })
test('tampered input hash is blocked',()=>{ const f=fixture(); fs.appendFileSync(path.join(f.root,'handoffs/wave-01/inputs/wave-01-chunk-01.input.jsonl'),'{}\n'); const result=run(f.root,true); assert.equal(result.status,2); assert.match(result.stdout,/input_sha_mismatch/u) })
test('archive inventory rejects duplicate ZIP entries',()=>{ const dir=fs.mkdtempSync(path.join(os.tmpdir(),'radar-zip-')); const zip=path.join(dir,'duplicate.zip'); const ps=`Add-Type -AssemblyName System.IO.Compression; Add-Type -AssemblyName System.IO.Compression.FileSystem; $z=[System.IO.Compression.ZipFile]::Open('${zip.replace(/'/gu,"''")}',[System.IO.Compression.ZipArchiveMode]::Create); 1..2|%{$e=$z.CreateEntry('same.txt');$w=[IO.StreamWriter]::new($e.Open());$w.Write('x');$w.Dispose()};$z.Dispose()`; execFileSync('powershell',['-NoProfile','-Command',ps]); assert.throws(()=>archiveInventory(zip),/Duplicate ZIP entry/u) })
test('archive inventory rejects symlink entries',()=>{ const dir=fs.mkdtempSync(path.join(os.tmpdir(),'radar-zip-')); const zip=path.join(dir,'symlink.zip'); const ps=`Add-Type -AssemblyName System.IO.Compression; Add-Type -AssemblyName System.IO.Compression.FileSystem; $z=[System.IO.Compression.ZipFile]::Open('${zip.replace(/'/gu,"''")}',[System.IO.Compression.ZipArchiveMode]::Create);$e=$z.CreateEntry('link');$e.ExternalAttributes=([int]0xA000 -shl 16);$w=[IO.StreamWriter]::new($e.Open());$w.Write('target');$w.Dispose();$z.Dispose()`; execFileSync('powershell',['-NoProfile','-Command',ps]); assert.throws(()=>archiveInventory(zip),/symlink/u) })
test('write-like flags are rejected by committed scripts',()=>{ for(const script of ['prepare-radar-research-assessment-bulk-v02.mjs','assemble-radar-research-assessment-bulk-v02.mjs']) { const result=spawnSync(process.execPath,[path.join(repo,'scripts/radar',script),'--apply'],{encoding:'utf8'}); assert.notEqual(result.status,0); assert.match(result.stderr,/rejects --apply/u) } })
test('committed code has no Payload, PostgreSQL, Works mutation, or production apply path',()=>{ const files=['lib/research-assessment-handoff-v02.mjs','prepare-radar-research-assessment-bulk-v02.mjs','assemble-radar-research-assessment-bulk-v02.mjs']; const text=files.map(f=>fs.readFileSync(path.join(repo,'scripts/radar',f),'utf8')).join('\n'); assert.doesNotMatch(text,/getPayload|payload\.update|UPDATE\s+works|productionApplyAuthorized:\s*true/iu) })
test('ZIP traversal entries are rejected',()=>{ const dir=fs.mkdtempSync(path.join(os.tmpdir(),'radar-zip-')); const zip=path.join(dir,'traversal.zip'); const ps=`Add-Type -AssemblyName System.IO.Compression; Add-Type -AssemblyName System.IO.Compression.FileSystem; $z=[System.IO.Compression.ZipFile]::Open('${zip.replace(/'/gu,"''")}',[System.IO.Compression.ZipArchiveMode]::Create);$e=$z.CreateEntry('../escape.txt');$w=[IO.StreamWriter]::new($e.Open());$w.Write('x');$w.Dispose();$z.Dispose()`; execFileSync('powershell',['-NoProfile','-Command',ps]); assert.throws(()=>archiveInventory(zip),/Unsafe ZIP entry/u) })
test('closed-world package verification rejects missing manifests, unlisted files, and bad hashes',()=>{ const acceptance={waveCount:1,rowsPerWave:1,rowCount:1,laneCounts:{}}; const missing=fs.mkdtempSync(path.join(os.tmpdir(),'radar-package-')); assert.throws(()=>loadResearchPackage(missing,'',path.join(missing,'scratch'),acceptance),/review-manifest.json missing/u); const unlisted=fs.mkdtempSync(path.join(os.tmpdir(),'radar-package-')); fs.writeFileSync(path.join(unlisted,'review-manifest.json'),'[]'); fs.writeFileSync(path.join(unlisted,'extra.txt'),'x'); assert.throws(()=>loadResearchPackage(unlisted,'',path.join(unlisted,'scratch'),acceptance),/Unlisted payload file/u); const bad=fs.mkdtempSync(path.join(os.tmpdir(),'radar-package-')); fs.writeFileSync(path.join(bad,'payload.txt'),'x'); fs.writeFileSync(path.join(bad,'review-manifest.json'),JSON.stringify([{file:'payload.txt',bytes:1,sha256:'0'.repeat(64)}])); assert.throws(()=>loadResearchPackage(bad,'',path.join(bad,'scratch'),acceptance),/Review manifest mismatch/u) })
test('outer ZIP SHA mismatch is rejected before extraction',()=>{ const dir=fs.mkdtempSync(path.join(os.tmpdir(),'radar-zip-')); const zip=path.join(dir,'one.zip'); fs.writeFileSync(path.join(dir,'one.txt'),'x'); execFileSync('tar',['-a','-cf',zip,'-C',dir,'one.txt']); assert.throws(()=>loadResearchPackage(zip,'0'.repeat(64),path.join(dir,'scratch'),{waveCount:1}),/Outer research ZIP SHA-256 mismatch/u) })
test('real accepted ZIP preparation is deterministic when explicitly supplied', { skip: !process.env.RADAR_RESEARCH_REVIEW_ZIP }, ()=>{ const prepare=path.join(repo,'scripts/radar/prepare-radar-research-assessment-bulk-v02.mjs'); const acceptance=path.join(repo,'scripts/radar/fixtures/radar-research-assessment-accepted-0001-v02.json'); const base=path.join(repo,'data_local','test-runs','radar-v02-determinism'); const outputs=[`${base}-a`,`${base}-b`]; for(const out of outputs){ fs.rmSync(out,{recursive:true,force:true}); const result=spawnSync(process.execPath,[prepare,'--input',process.env.RADAR_RESEARCH_REVIEW_ZIP,'--expected-sha256',process.env.RADAR_RESEARCH_REVIEW_SHA,'--acceptance',acceptance,'--out-dir',out],{encoding:'utf8'}); assert.equal(result.status,0,result.stderr) } const a=JSON.parse(fs.readFileSync(path.join(outputs[0],'package-manifest.json'))); const b=JSON.parse(fs.readFileSync(path.join(outputs[1],'package-manifest.json'))); delete a.generatedAt; delete b.generatedAt; assert.deepEqual(a,b); assert.equal(a.waveCount,10); assert.equal(a.chunkCount,100); assert.equal(a.responseSlotCount,100); for(const out of outputs) fs.rmSync(out,{recursive:true,force:true}) })