import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const preflight = readFileSync('scripts/radar/prepare-radar-unified-release-production-0575-v01.ps1', 'utf8')
const authorize = readFileSync('scripts/radar/authorize-radar-unified-release-production-0575-v02.ps1', 'utf8')
const executor = readFileSync('scripts/radar/execute-radar-unified-release-production-0575-v01.ps1', 'utf8')
const helper = readFileSync('scripts/radar/lib/radar-unified-release-production-0575-v01.ps1', 'utf8')

test('production preflight is bound to the accepted lab, evidence and release', () => {
  assert.match(preflight, /6cdc29e28236f487a6e762a5c8871c681a870810/u)
  assert.match(preflight, /069e2d54055c8c8099ac8f37092e2bdb2b3e060c/u)
  assert.match(preflight, /728ad2da5f7d3aba03f652b9fd701157b06793ee/u)
  assert.match(preflight, /RADAR-UNIFIED-RATING-RELEASE-0575-0001/u)
  assert.match(preflight, /59dc908a447500adb39ef9f72bde306268fdf24ec85fdaaeb418dee0fb9be09f/u)
  assert.match(preflight, /e45673fa881d6b3faea0aab0dbfc00cdee29d7ad536b9ccd5b40dfd01f24317d/u)
  assert.match(preflight, /4dcf9e6790fa7175f18b7c91ed3b2f6522ec6d87c623183f0369491b06123605/u)
  assert.match(preflight, /2847b48eb08c2409c94e0380e6351d778421db13466f17138d2a64b20774eef4/u)
  assert.match(preflight, /b2363f319233c23c0c9c96a77cb5fec47990b1c9fbf125d847a291baef9835bb/u)
})

test('production preflight remains read-only and emits an unprivileged candidate', () => {
  assert.match(preflight, /ExpectedWorks = 35615/u)
  assert.match(preflight, /pg_dump -Fc --no-owner --no-privileges/u)
  assert.match(preflight, /source-post-backup-table-counts/u)
  assert.match(preflight, /source-post-backup-protected-fingerprints/u)
  assert.match(preflight, /sourceDatabaseWrite = \$false/u)
  assert.match(preflight, /migrationApplied = \$false/u)
  assert.match(preflight, /publicRecordsWritten = 0/u)
  assert.match(preflight, /publicRatingsWritten = 0/u)
  assert.match(preflight, /productionAuthorization = \$false/u)
  assert.match(preflight, /accept_read_only_production_candidate_preflight_0575_v01/u)
  assert.doesNotMatch(preflight, /pnpm\s+(?:exec\s+)?payload\s+migrate/u)
  assert.doesNotMatch(preflight, /run-unified-release.*import/u)
  assert.doesNotMatch(preflight, /docker\s+rm.*baihepailei-postgres/u)
})

test('merged-main authorization binds candidate, backup, release and critical code', () => {
  assert.match(authorize, /0b18c33987abe2c2eb0c2280acee789415396903d697aface2523312a334de31/u)
  assert.match(authorize, /ea0b1cb68c9f1fde91e5e9f10c12957469b30c37a29097c57cb18fa8b5b13751/u)
  assert.match(authorize, /ExpectedMainHead/u)
  assert.match(authorize, /origin\/main/u)
  assert.match(authorize, /critical-production-code-SHA256SUMS/u)
  assert.match(authorize, /radar-unified-release-production-0575-v01\.ps1/u)
  assert.match(authorize, /run-unified-release-production-import-0575-v01\.mjs/u)
  assert.match(authorize, /radar-unified-release-production-marker\/route\.ts/u)
  assert.match(authorize, /readyForExplicitApply = \$true/u)
  assert.match(authorize, /productionAuthorization = \$false/u)
  assert.match(authorize, /sourceDatabaseWrite = \$false/u)
  assert.doesNotMatch(authorize, /pnpm\s+(?:exec\s+)?payload\s+migrate/u)
})

test('executor rehearses the exact fresh backup before source writes', () => {
  assert.match(executor, /pg_dump -Fc --no-owner --no-privileges/u)
  assert.match(executor, /pg_restore/u)
  assert.match(executor, /rehearsalPlanPassed/u)
  assert.match(executor, /rehearsalApplyPassed/u)
  assert.match(executor, /rehearsalVerifyPassed/u)
  assert.match(executor, /Invoke-RadarImporter 'plan'/u)
  assert.match(executor, /Invoke-RadarImporter 'apply'/u)
  assert.match(executor, /Invoke-RadarImporter 'verify'/u)
  assert.match(executor, /source final preflight counts/u)
  assert.match(executor, /source final preflight fingerprints/u)
  const promptIndex = executor.indexOf("$typedConfirm = Read-Host")
  const sourceMarkerIndex = executor.indexOf('New-RadarApplyMarker $SourcePostgresContainer')
  assert.ok(promptIndex > 0)
  assert.ok(sourceMarkerIndex > promptIndex)
})

test('executor uses an atomic advisory transaction lock and durable apply marker', () => {
  assert.match(executor, /pg_try_advisory_xact_lock/u)
  assert.match(executor, /radar_unified_release_apply_control/u)
  assert.match(executor, /state IN \('started', 'completed', 'failed'\)/u)
  assert.match(executor, /durableMarkerCreated/u)
  assert.match(executor, /durableMarkerCompleted/u)
  assert.match(executor, /Set-RadarApplyMarkerState[\s\S]*'failed'/u)
  assert.match(executor, /automaticRetryAllowed = \$false/u)
  assert.match(executor, /automaticRollbackExecuted = \$false/u)
  assert.match(executor, /productionRollbackAuthorized = \$false/u)
  assert.doesNotMatch(helper, /pg_sleep/u)
})

test('executor verifies exact migration and storage deltas', () => {
  assert.match(executor, /ExpectedLegacySchemaSha256 = 'bb4bc33661c989e91dc7fda964f4023f3ef175582fe9e95449f568348eb17c7d'/u)
  assert.match(executor, /20260802_062015_radar_public_record_evidence_role_v01/u)
  assert.match(executor, /public\.payload_migrations[\s\S]{0,220}\$beforeValue \+ 6/u)
  assert.match(executor, /public\.audit_events[\s\S]{0,220}\$beforeValue \+ 1150/u)
  assert.match(executor, /public\.users_sessions[\s\S]{0,220}\$beforeValue \+ 1/u)
  assert.match(executor, /public\.radar_unified_release_apply_control' = 1/u)
  assert.match(executor, /Assert-RadarMapsEqual \$sourceBaseline\.Fingerprints \$sourcePost\.Fingerprints/u)
  assert.match(executor, /publicRecords = 575/u)
  assert.match(executor, /publicRatings = 575/u)
})

test('failure boundary never performs automatic rollback or destructive git cleanup', () => {
  assert.doesNotMatch(executor, /git reset --hard/u)
  assert.doesNotMatch(executor, /git clean/u)
  assert.doesNotMatch(executor, /docker exec[^\n]*\$SourcePostgresContainer[^\n]*pg_restore/u)
  assert.match(executor, /writerContainersIntentionallyLeftPaused/u)
  assert.match(executor, /automaticRollbackExecuted = \$false/u)
  assert.match(executor, /automaticRetryAllowed = \$false/u)
})
