import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const page = read('src/app/(frontend)/me/review/public-catalog/page.tsx')
const contentPage = read('src/app/(frontend)/me/review/content/page.tsx')
const legacyWorkEditorRedirect = read('src/app/(frontend)/me/review/content/works/[id]/page.tsx')
const studioWorkEditor = read('src/app/(frontend)/me/studio/works/[id]/page.tsx')
const reviewUtils = read('src/app/(frontend)/me/review/content/review-utils.ts')
const mergedWork = read('src/lib/mergedWork.ts')
const feedbackPage = read('src/app/(frontend)/me/review/feedback/page.tsx')
const feedbackDetailPage = read('src/app/(frontend)/me/review/feedback/[id]/page.tsx')
const works = read('src/collections/Works.ts')
const creators = read('src/collections/Creators.ts')
const organizations = read('src/collections/Organizations.ts')
const reviewFields = read('src/collections/fields/contentReview.ts')
const css = read('src/app/(frontend)/review-workbench.css')
const editorCss = read('src/app/(frontend)/review-editor.css')

function functionBody(source, name, nextName) {
  const start = source.indexOf(`async function ${name}`)
  const end = source.indexOf(`async function ${nextName}`, start + 1)
  assert.notEqual(start, -1, `missing function ${name}`)
  return source.slice(start, end === -1 ? source.length : end)
}

test('review workbench is paginated and queries the database', () => {
  assert.match(page, /limit: filters\.perPage/u)
  assert.match(page, /page: filters\.page/u)
  assert.match(page, /buildWhere\(filters\)/u)
  assert.doesNotMatch(page, /limit: 2000/u)
  assert.match(css, /\.review-row-facts/u)
})

test('single-entry review actions leave publication and grade untouched', () => {
  assert.match(page, /updateReviewAction/u)
  assert.match(page, /humanReviewedAt/u)
  assert.match(page, /humanReviewedBy/u)
  assert.match(page, /decision === 'reviewed'/u)
  assert.doesNotMatch(page, /data\.rank\s*=/u)
  assert.doesNotMatch(page, /data\.status\s*=/u)
  assert.match(works, /name: 'humanReviewNote'/u)
})

test('research queues remain clearly separate from formal ratings', () => {
  assert.match(page, /radar-research-records/u)
  assert.match(page, /研究建议，不等于正式评级/u)
  assert.match(page, /不会把 25,048 条研究建议写进正式评级/u)
})

test('unified content workbench covers works, creators and organizations', () => {
  assert.match(contentPage, /type ContentCollection = 'works' \| 'creators' \| 'organizations'/u)
  assert.match(contentPage, /saveContentAction/u)
  assert.match(contentPage, /AI 已评估只说明机器整理已经存在，不代表人工通过/u)
  assert.match(contentPage, /canonicalContentUrl/u)
  assert.match(contentPage, /站内完整编辑/u)
  assert.match(contentPage, /value="approve"/u)
  assert.match(contentPage, /value="reject"/u)
  assert.match(contentPage, /limit: filters\.perPage/u)
  assert.match(contentPage, /AI 建议：/u)
  assert.match(creators, /contentReviewFields/u)
  assert.match(organizations, /contentReviewFields/u)
  assert.match(reviewFields, /name: 'reviewOrigin'/u)
  assert.match(reviewFields, /value: 'ai_assessed'/u)
  assert.match(css, /\.review-content-form/u)
})

test('content review defaults to a pending queue and keeps processed history separate', () => {
  assert.match(contentPage, /type ReviewQueue = 'pending' \| 'processed' \| 'all'/u)
  assert.match(contentPage, /requestedQueue === 'processed' \|\| requestedQueue === 'all' \? requestedQueue : 'pending'/u)
  assert.match(contentPage, /reviewStatus: \{ equals: 'pending' \}/u)
  assert.match(contentPage, /reviewStatus: \{ in: processedStatuses \}/u)
  assert.match(contentPage, /draftCount/u)
  assert.match(contentPage, /draft: true/u)
  assert.match(contentPage, />待处理</u)
  assert.match(contentPage, />已处理</u)
  assert.match(contentPage, /通过并移入已处理/u)
  assert.match(editorCss, /\.review-queue-tabs/u)
})

test('merged duplicate works require explicit markers or retired legacy rows', () => {
  assert.match(reviewUtils, /from '@\/lib\/mergedWork'/u)
  assert.match(mergedWork, /mergedIntoWorkId/u)
  assert.match(mergedWork, /mergedIntoWorkTitle/u)
  assert.match(mergedWork, /doc\.reviewStatus === 'deprecated' \|\| doc\.status === 'archived'/u)
  assert.match(mergedWork, /duplicate of work/u)
  assert.match(contentPage, /isMergedDuplicateWork\(current\)/u)
  assert.match(contentPage, /reviewError', 'merged_duplicate'/u)
  assert.match(contentPage, /这个旧条目已经合并，不可继续保存或审核/u)
  assert.match(contentPage, /draft: false/u)
  assert.match(contentPage, /Content review update failed/u)
})

test('dedicated content studio handles routine corrections while the legacy route redirects', () => {
  assert.match(legacyWorkEditorRedirect, /\/me\/studio\/works\//u)
  assert.match(studioWorkEditor, /站内内容管理 · 作品编辑/u)
  assert.match(studioWorkEditor, /aliasesFromText/u)
  assert.match(studioWorkEditor, /sourceLinksFromText/u)
  assert.match(studioWorkEditor, /localizedTitlesFromText/u)
  assert.match(studioWorkEditor, /firstPublishedPrecision/u)
  assert.match(studioWorkEditor, /firstPartyStudio: true/u)
  assert.match(studioWorkEditor, /draft: false/u)
  assert.doesNotMatch(studioWorkEditor, /riskMatrix/u)
  assert.doesNotMatch(studioWorkEditor, /Payload 高级维护/u)
  assert.match(editorCss, /\.review-editor-section/u)
  assert.match(editorCss, /\.review-editor-submit/u)
})

test('user submissions have a first-party queue with explicit accept and reject decisions', () => {
  assert.match(feedbackPage, /collection: 'feedback-submissions'/u)
  assert.match(feedbackPage, /value="accepted"/u)
  assert.match(feedbackPage, /value="rejected"/u)
  assert.match(feedbackPage, /value="needs_information"/u)
  assert.match(feedbackPage, /不会自动覆盖作品等级/u)
  assert.match(feedbackPage, /reviewWorkbench: true/u)
  assert.match(feedbackPage, /reviewError/u)
  assert.match(feedbackPage, /站内完整详情/u)
  assert.doesNotMatch(feedbackPage, /采纳、未采纳或要求补充材料时必须填写/u)
  assert.match(feedbackDetailPage, /用户反馈完整详情/u)
  assert.match(feedbackDetailPage, /全部证据链接/u)
})

test('feedback forms default to active work and move completed decisions into history', () => {
  assert.match(feedbackPage, /type FeedbackQueue = 'active' \| 'processed' \| 'all'/u)
  assert.match(feedbackPage, /workflowStatus: \{ in: activeStatuses \}/u)
  assert.match(feedbackPage, /workflowStatus: \{ in: processedStatuses \}/u)
  assert.match(feedbackPage, /完成态表单会自动离开待处理队列/u)
  assert.match(feedbackPage, /采纳反馈并移入已处理/u)
  assert.match(feedbackPage, /驳回并移入已处理/u)
  assert.match(feedbackPage, /站内编辑关联作品/u)
  assert.match(feedbackPage, /returnTo=\$\{encodeURIComponent\(currentReturnTo\)\}/u)
  assert.match(reviewUtils, /isFeedbackQueue/u)
})
