import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const evidencePage = read('src/app/(frontend)/me/review/public-catalog/page.tsx')
const contentPage = read('src/app/(frontend)/me/review/content/page.tsx')
const contentActions = read('src/app/(frontend)/me/review/content/review-actions.ts')
const contentDetail = read('src/app/(frontend)/me/review/content/review-detail.tsx')
const workReviewRoute = read('src/app/(frontend)/me/review/content/works/[id]/page.tsx')
const genericReviewRoute = read('src/app/(frontend)/me/review/content/[collection]/[id]/page.tsx')
const studioWorkEditor = read('src/app/(frontend)/me/studio/works/[id]/page.tsx')
const reviewUtils = read('src/app/(frontend)/me/review/content/review-utils.ts')
const mergedWork = read('src/lib/mergedWork.ts')
const feedbackPage = read('src/app/(frontend)/me/review/feedback/page.tsx')
const feedbackActions = read('src/app/(frontend)/me/review/feedback/review-actions.ts')
const feedbackDetail = read('src/app/(frontend)/me/review/feedback/[id]/page.tsx')
const decisions = read('src/app/(frontend)/me/review/_components/ReviewDecisionButtons.tsx')
const works = read('src/collections/Works.ts')
const creators = read('src/collections/Creators.ts')
const organizations = read('src/collections/Organizations.ts')
const reviewFields = read('src/collections/fields/contentReview.ts')
const css = read('src/app/(frontend)/review-workbench.css')
const editorCss = read('src/app/(frontend)/review-editor.css')

test('review workbench is paginated and queries the database', () => {
  assert.match(evidencePage, /limit: filters\.perPage/u)
  assert.match(evidencePage, /page: filters\.page/u)
  assert.match(evidencePage, /buildWhere\(filters\)/u)
  assert.doesNotMatch(evidencePage, /limit: 2000/u)
  assert.match(css, /\.review-row-facts/u)
})

test('single-entry evidence review leaves publication and grade untouched', () => {
  assert.match(evidencePage, /updateReviewAction/u)
  assert.match(evidencePage, /humanReviewedAt/u)
  assert.match(evidencePage, /humanReviewedBy/u)
  assert.match(evidencePage, /decision === 'reviewed'/u)
  assert.doesNotMatch(evidencePage, /data\.rank\s*=|data\.status\s*=/u)
  assert.match(works, /name: 'humanReviewNote'/u)
})

test('research queues remain separate from formal ratings', () => {
  assert.match(evidencePage, /radar-research-records/u)
  assert.match(evidencePage, /研究建议，不等于正式评级/u)
  assert.match(evidencePage, /不会把 25,048 条研究建议写进正式评级/u)
})

test('content queue only starts dedicated reviews', () => {
  assert.match(contentPage, /type ContentCollection/u)
  assert.match(contentPage, /beginContentReviewAction/u)
  assert.match(contentPage, /队列只负责进入审查/u)
  assert.match(contentPage, /开始审查/u)
  assert.match(contentPage, /查看审查记录/u)
  assert.match(contentPage, /limit: filters\.perPage/u)
  assert.match(contentPage, /尚无 AI 建议/u)
  assert.doesNotMatch(contentPage, /name="rank"|name="note"|value="approve"|value="reject"/u)
  assert.doesNotMatch(contentPage, /\/me\/studio\/works\//u)
  assert.match(creators, /contentReviewFields/u)
  assert.match(organizations, /contentReviewFields/u)
  assert.match(reviewFields, /name: 'reviewOrigin'/u)
  assert.match(reviewFields, /value: 'ai_assessed'/u)
})

test('content review defaults to pending and keeps processed history separate', () => {
  assert.match(contentPage, /type ReviewQueue = 'pending' \| 'processed' \| 'all'/u)
  assert.match(contentPage, /requestedQueue === 'processed' \|\| requestedQueue === 'all' \? requestedQueue : 'pending'/u)
  assert.match(contentPage, /reviewStatus: \{ equals: 'pending' \}/u)
  assert.match(contentPage, /reviewStatus: \{ in: processedStatuses \}/u)
  assert.match(contentPage, /draftCount/u)
  assert.doesNotMatch(contentPage, /draft: true/u)
  assert.match(contentPage, />待处理</u)
  assert.match(contentPage, />已处理</u)
  assert.match(editorCss, /\.review-queue-tabs/u)
})

test('dedicated content review pages contain preview and guarded decisions', () => {
  assert.match(workReviewRoute, /ContentReviewDetail/u)
  assert.match(genericReviewRoute, /ContentReviewDetail/u)
  assert.match(contentDetail, /这是独立审核页，不是正式内容编辑器/u)
  assert.match(contentDetail, /展开站内前台预览/u)
  assert.match(contentDetail, /<iframe/u)
  assert.match(contentDetail, /ReviewDecisionButtons/u)
  assert.match(contentDetail, /只保存审核记录/u)
  assert.match(contentDetail, /通过并移入已处理/u)
  assert.match(contentDetail, /驳回并标记争议/u)
  assert.match(contentDetail, /review-editor-submit/u)
  assert.doesNotMatch(contentDetail, /\/me\/studio\/works\//u)
  assert.match(decisions, /useFormStatus/u)
  assert.match(decisions, /window\.confirm/u)
})

test('content decisions preserve publication and keep AI separate', () => {
  assert.match(contentActions, /saveContentReviewAction/u)
  assert.match(contentActions, /intent === 'approve'/u)
  assert.match(contentActions, /intent === 'reject'/u)
  assert.match(contentActions, /data\.humanAssessment/u)
  assert.match(contentActions, /data\.ratingNotice = 'manual_reviewed'/u)
  assert.doesNotMatch(contentActions, /data\._status|data\.catalogStatus|isLiteVisible|isFullVisible/u)
  assert.doesNotMatch(contentActions, /data\.radarAssessment/u)
})

test('merged duplicate works redirect review to the canonical record', () => {
  assert.match(reviewUtils, /from '@\/lib\/mergedWork'/u)
  assert.match(mergedWork, /mergedIntoWorkId/u)
  assert.match(mergedWork, /mergedIntoWorkTitle/u)
  assert.match(mergedWork, /const retired = doc\.reviewStatus === 'deprecated'/u)
  assert.match(mergedWork, /doc\.catalogStatus === 'archived'/u)
  assert.match(mergedWork, /doc\.status === 'archived'/u)
  assert.match(mergedWork, /duplicate of work/u)
  assert.match(contentActions, /isMergedDuplicateWork\(current\)/u)
  assert.match(contentActions, /reviewError: 'merged_duplicate'/u)
  assert.match(contentDetail, /旧条目已经合并/u)
})

test('Studio remains available but is not linked from review queues', () => {
  assert.match(studioWorkEditor, /站内内容管理 · 作品编辑/u)
  assert.match(studioWorkEditor, /aliasesFromText/u)
  assert.match(studioWorkEditor, /sourceLinksFromText/u)
  assert.match(studioWorkEditor, /localizedTitlesFromText/u)
  assert.match(studioWorkEditor, /firstPublishedPrecision/u)
  assert.match(studioWorkEditor, /firstPartyStudio: true/u)
  assert.match(studioWorkEditor, /draft: false/u)
  assert.doesNotMatch(studioWorkEditor, /riskMatrix/u)
  assert.match(editorCss, /\.review-editor-section/u)
  assert.match(editorCss, /\.review-editor-submit/u)
  assert.doesNotMatch(contentPage, /\/me\/studio\/works\//u)
  assert.doesNotMatch(feedbackPage, /\/me\/studio\/works\//u)
})

test('feedback queue starts reviews while decisions live on the detail page', () => {
  assert.match(feedbackPage, /collection: 'feedback-submissions'/u)
  assert.match(feedbackPage, /beginFeedbackReviewAction/u)
  assert.match(feedbackPage, /开始核查/u)
  assert.match(feedbackPage, /继续核查/u)
  assert.doesNotMatch(feedbackPage, /value="accepted"|value="rejected"|value="needs_information"|accept_create_draft/u)
  assert.match(feedbackDetail, /用户反馈 · 独立核查页/u)
  assert.match(feedbackDetail, /ReviewDecisionButtons/u)
  assert.match(feedbackDetail, /只保存审核说明/u)
  assert.match(feedbackDetail, /要求补充材料/u)
  assert.match(feedbackDetail, /采纳并生成草稿/u)
  assert.match(feedbackDetail, /驳回/u)
  assert.match(feedbackDetail, /归档/u)
  assert.match(feedbackDetail, /关联作品预览/u)
  assert.doesNotMatch(feedbackDetail, /编辑关联作品|现在编辑关联作品/u)
})

test('feedback decisions create factual drafts and notify the account timeline', () => {
  assert.match(feedbackActions, /newWorkProposalToWorkTransfer/u)
  assert.match(feedbackActions, /feedbackIntake: true/u)
  assert.match(feedbackActions, /rank: 'unknown'/u)
  assert.match(feedbackActions, /ratingNotice: 'none'/u)
  assert.doesNotMatch(feedbackActions, /radarAssessment:/u)
  assert.match(feedbackActions, /revalidatePath\('\/me\/messages'\)/u)
  assert.match(feedbackActions, /workflowStatus: 'accepted'/u)
  assert.match(feedbackActions, /workflowStatus: 'triaging'/u)
})

test('feedback forms keep active and processed queues separate', () => {
  assert.match(feedbackPage, /type FeedbackQueue = 'active' \| 'processed' \| 'all'/u)
  assert.match(feedbackPage, /workflowStatus: \{ in: activeStatuses \}/u)
  assert.match(feedbackPage, /workflowStatus: \{ in: processedStatuses \}/u)
  assert.match(feedbackPage, /采纳、驳回和归档的表单都保存在/u)
  assert.match(reviewUtils, /isFeedbackQueue/u)
})
