import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const evidencePage = read('src/app/(frontend)/me/review/public-catalog/page.tsx')
const contentPage = read('src/app/(frontend)/me/review/content/page.tsx')
const contentActions = read('src/app/(frontend)/me/review/content/review-actions.ts')
const aiReviewDetail = read('src/app/(frontend)/me/review/content/ai-work-review-detail.tsx')
const workReviewRoute = read('src/app/(frontend)/me/review/content/works/[id]/page.tsx')
const genericReviewRoute = read('src/app/(frontend)/me/review/content/[collection]/[id]/page.tsx')
const studioWorkEditor = read('src/app/(frontend)/me/studio/works/[id]/page.tsx')
const reviewUtils = read('src/app/(frontend)/me/review/content/review-utils.ts')
const mergedWork = read('src/lib/mergedWork.ts')
const feedbackPage = read('src/app/(frontend)/me/review/feedback/page.tsx')
const feedbackActions = read('src/app/(frontend)/me/review/feedback/review-actions.ts')
const feedbackDetail = read('src/app/(frontend)/me/review/feedback/[id]/page.tsx')
const decisions = read('src/app/(frontend)/me/review/_components/ReviewDecisionButtons.tsx')
const works = read('src/collections/Works.ts')
const css = read('src/app/(frontend)/review-workbench.css')
const editorCss = read('src/app/(frontend)/review-editor.css')

test('evidence review remains paginated and database-backed', () => {
  assert.match(evidencePage, /limit: filters\.perPage/u)
  assert.match(evidencePage, /page: filters\.page/u)
  assert.match(evidencePage, /buildWhere\(filters\)/u)
  assert.doesNotMatch(evidencePage, /limit: 2000/u)
  assert.match(css, /\.review-row-facts/u)
})

test('single-entry evidence review leaves publication and grade untouched', () => {
  assert.match(evidencePage, /updateReviewAction/u)
  assert.match(evidencePage, /humanReviewedAt/u)
  assert.match(evidencePage, /humanReviewedBy/u)
  assert.match(evidencePage, /decision === 'reviewed'/u)
  assert.doesNotMatch(evidencePage, /data\.rank\s*=|data\.status\s*=/u)
  assert.match(works, /name: 'humanReviewNote'/u)
})

test('research queues remain separate from formal ratings', () => {
  assert.match(evidencePage, /radar-research-records/u)
  assert.match(evidencePage, /研究建议，不等于正式评级/u)
  assert.match(evidencePage, /不会把 25,048 条研究建议写进正式评级/u)
})

test('AI review queue contains only controlled AI-rated works', () => {
  assert.match(contentPage, /AI 评级人工复核/u)
  assert.match(contentPage, /已有 AI 评级，等待人工确认/u)
  assert.match(contentPage, /'radarAssessment\.assessedAt': \{ exists: true \}/u)
  assert.match(contentPage, /ratingNotice: \{ equals: 'ai_synthesized_pending_review' \}/u)
  assert.match(contentPage, /reviewStatus: \{ equals: 'pending' \}/u)
  assert.match(contentPage, /普通未评估作品、创作者和机构不再进入这个队列/u)
  assert.match(contentPage, /开始人工复核/u)
  assert.match(contentPage, /查看人工复核记录/u)
  assert.doesNotMatch(contentPage, /type ContentCollection|collectionMeta|creators|organizations/u)
  assert.doesNotMatch(contentPage, /name="rank"|name="note"|value="approve"|value="reject"/u)
})

test('AI review queue keeps pending, processed and all history separate', () => {
  assert.match(contentPage, /type ReviewQueue = 'pending' \| 'processed' \| 'all'/u)
  assert.match(contentPage, /requestedQueue === 'processed' \|\| requestedQueue === 'all' \? requestedQueue : 'pending'/u)
  assert.match(contentPage, /reviewStatus: \{ in: \['reviewed', 'disputed'\] \}/u)
  assert.match(contentPage, />待人工复核</u)
  assert.match(contentPage, />已处理</u)
  assert.match(contentPage, />全部 AI 评级作品</u)
  assert.match(editorCss, /\.review-queue-tabs/u)
})

test('dedicated AI work review page contains preview and guarded human decisions', () => {
  assert.match(workReviewRoute, /AIWorkReviewDetail/u)
  assert.match(genericReviewRoute, /notFound/u)
  assert.match(aiReviewDetail, /已有受控 AI 评级、尚无人工评级/u)
  assert.match(aiReviewDetail, /展开作品前台实时预览/u)
  assert.match(aiReviewDetail, /\?preview=1/u)
  assert.match(aiReviewDetail, /ReviewDecisionButtons/u)
  assert.match(aiReviewDetail, /只保存人工复核记录/u)
  assert.match(aiReviewDetail, /确认人工评级并通过/u)
  assert.match(aiReviewDetail, /驳回 AI 建议并标记争议/u)
  assert.match(aiReviewDetail, /review-editor-submit/u)
  assert.doesNotMatch(aiReviewDetail, /\/me\/studio\/works\//u)
  assert.match(decisions, /useFormStatus/u)
  assert.match(decisions, /window\.confirm/u)
})

test('human decisions preserve publication, stage and AI records', () => {
  assert.match(contentActions, /saveContentReviewAction/u)
  assert.match(contentActions, /current\.radarAssessment\?\.assessedAt/u)
  assert.match(contentActions, /intent === 'approve'/u)
  assert.match(contentActions, /intent === 'reject'/u)
  assert.match(contentActions, /data\.humanAssessment/u)
  assert.match(contentActions, /data\.ratingNotice = 'manual_reviewed'/u)
  assert.doesNotMatch(contentActions, /data\._status|data\.catalogStatus|isLiteVisible|isFullVisible/u)
  assert.doesNotMatch(contentActions, /data\.radarAssessment/u)
})

test('merged duplicate works redirect review to the canonical record', () => {
  assert.match(reviewUtils, /from '@\/lib\/mergedWork'/u)
  assert.match(mergedWork, /mergedIntoWorkId/u)
  assert.match(mergedWork, /mergedIntoWorkTitle/u)
  assert.match(contentActions, /isMergedDuplicateWork\(current\)/u)
  assert.match(contentActions, /reviewError: 'merged_duplicate'/u)
  assert.match(aiReviewDetail, /旧条目已经合并/u)
})

test('Studio remains available but is not linked from review queues', () => {
  assert.match(studioWorkEditor, /站内内容管理 · 作品编辑/u)
  assert.match(studioWorkEditor, /aliasesFromText/u)
  assert.match(studioWorkEditor, /sourceLinksFromText/u)
  assert.match(studioWorkEditor, /firstPartyStudio: true/u)
  assert.match(editorCss, /\.review-editor-section/u)
  assert.match(editorCss, /\.review-editor-submit/u)
  assert.doesNotMatch(contentPage, /\/me\/studio\/works\//u)
  assert.doesNotMatch(feedbackPage, /\/me\/studio\/works\//u)
})

test('feedback queue starts reviews while decisions live on the detail page', () => {
  assert.match(feedbackPage, /collection: 'feedback-submissions'/u)
  assert.match(feedbackPage, /beginFeedbackReviewAction/u)
  assert.match(feedbackPage, /开始核查/u)
  assert.match(feedbackPage, /继续核查/u)
  assert.doesNotMatch(feedbackPage, /value="accepted"|value="rejected"|value="needs_information"|accept_create_draft/u)
  assert.match(feedbackDetail, /用户反馈 · 独立核查页/u)
  assert.match(feedbackDetail, /ReviewDecisionButtons/u)
  assert.match(feedbackDetail, /要求补充材料/u)
  assert.match(feedbackDetail, /驳回/u)
  assert.match(feedbackDetail, /归档/u)
  assert.match(feedbackDetail, /关联作品预览/u)
})

test('accepted new-work feedback creates a public temporary work and notifies the account timeline', () => {
  assert.match(feedbackActions, /newWorkProposalToWorkTransfer/u)
  assert.match(feedbackActions, /feedbackIntake: true/u)
  assert.match(feedbackActions, /rank: 'unknown'/u)
  assert.match(feedbackActions, /ratingNotice: 'none'/u)
  assert.match(feedbackActions, /_status: 'published'/u)
  assert.match(feedbackActions, /catalogStatus: 'temporary'/u)
  assert.match(feedbackActions, /isLiteVisible: true/u)
  assert.match(feedbackActions, /isFullVisible: true/u)
  assert.doesNotMatch(feedbackActions, /radarAssessment:/u)
  assert.match(feedbackActions, /revalidatePath\('\/me\/messages'\)/u)
  assert.match(feedbackActions, /workflowStatus: 'accepted'/u)
})

test('feedback forms keep active and processed queues separate', () => {
  assert.match(feedbackPage, /type FeedbackQueue = 'active' \| 'processed' \| 'all'/u)
  assert.match(feedbackPage, /workflowStatus: \{ in: activeStatuses \}/u)
  assert.match(feedbackPage, /workflowStatus: \{ in: processedStatuses \}/u)
  assert.match(reviewUtils, /isFeedbackQueue/u)
})
